/**
 * Auto-generated Tailwind plugin for Vera design system
 * DO NOT EDIT MANUALLY - Generated by generateTailwindPlugin.ts
 */
// eslint-disable-next-line @typescript-eslint/no-require-imports
const plugin = require('tailwindcss/plugin');

/**
 * @param {import('../veraUI.types').VeraThemeTokens} [config] Optional theme
 * document (the same standardized designTokens.json shape). When provided, its
 * values override the baked-in defaults at runtime, which is what enables
 * live theme updates in dev without regenerating this file.
 */

const veraUI = (config = {}) => {
  return plugin(
    ({ addUtilities, addBase, addVariant }) => {
      const fontSizeUtilities = {};
      const fontWeightUtilities = {};

      // Add custom variants
      addVariant('child', '& > *');

      // Add CSS variables for theme-aware colors
      addBase({
        ':host, :root': {
          '--vera-accent': config.colors?.light?.['accent'] ?? '#FFFFFF',
          '--vera-accent-light': config.colors?.light?.['accent'] ?? '#FFFFFF',
          '--vera-accent-dark': config.colors?.dark?.['accent'] ?? '#FFFFFF',
          '--vera-alert-background': config.colors?.light?.['alert-background'] ?? '#FFEEF2',
          '--vera-alert-background-light': config.colors?.light?.['alert-background'] ?? '#FFEEF2',
          '--vera-alert-background-dark': config.colors?.dark?.['alert-background'] ?? '#3E0004',
          '--vera-alert-background-hover':
            config.colors?.light?.['alert-background-hover'] ?? '#FEDFDF',
          '--vera-alert-background-hover-light':
            config.colors?.light?.['alert-background-hover'] ?? '#FEDFDF',
          '--vera-alert-background-hover-dark':
            config.colors?.dark?.['alert-background-hover'] ?? '#6E0000',
          '--vera-alert-text': config.colors?.light?.['alert-text'] ?? '#CD0000',
          '--vera-alert-text-light': config.colors?.light?.['alert-text'] ?? '#CD0000',
          '--vera-alert-text-dark': config.colors?.dark?.['alert-text'] ?? '#FEDFDF',
          '--vera-background': config.colors?.light?.['background'] ?? '#F5F0FD',
          '--vera-background-light': config.colors?.light?.['background'] ?? '#F5F0FD',
          '--vera-background-dark': config.colors?.dark?.['background'] ?? '#26044D',
          '--vera-border': config.colors?.light?.['border'] ?? '#E6E6E6',
          '--vera-border-light': config.colors?.light?.['border'] ?? '#E6E6E6',
          '--vera-border-dark': config.colors?.dark?.['border'] ?? '#333333',
          '--vera-dark-background': config.colors?.light?.['dark-background'] ?? '#202124',
          '--vera-dark-background-light': config.colors?.light?.['dark-background'] ?? '#202124',
          '--vera-dark-background-dark': config.colors?.dark?.['dark-background'] ?? '#202124',
          '--vera-dark-grey': config.colors?.light?.['dark-grey'] ?? '#333333',
          '--vera-dark-grey-light': config.colors?.light?.['dark-grey'] ?? '#333333',
          '--vera-dark-grey-dark': config.colors?.dark?.['dark-grey'] ?? '#333333',
          '--vera-dark-grey-hover': config.colors?.light?.['dark-grey-hover'] ?? '#292828',
          '--vera-dark-grey-hover-light': config.colors?.light?.['dark-grey-hover'] ?? '#292828',
          '--vera-dark-grey-hover-dark': config.colors?.dark?.['dark-grey-hover'] ?? '#292828',
          '--vera-dark-grey-opacity': config.colors?.light?.['dark-grey-opacity'] ?? '#333333CD',
          '--vera-dark-grey-opacity-light':
            config.colors?.light?.['dark-grey-opacity'] ?? '#333333CD',
          '--vera-dark-grey-opacity-dark':
            config.colors?.dark?.['dark-grey-opacity'] ?? '#333333CD',
          '--vera-disabled': config.colors?.light?.['disabled'] ?? '#E6E6E6',
          '--vera-disabled-light': config.colors?.light?.['disabled'] ?? '#E6E6E6',
          '--vera-disabled-dark': config.colors?.dark?.['disabled'] ?? '#333333',
          '--vera-error': config.colors?.light?.['error'] ?? '#E61D1D',
          '--vera-error-light': config.colors?.light?.['error'] ?? '#E61D1D',
          '--vera-error-dark': config.colors?.dark?.['error'] ?? '#F75959',
          '--vera-error-hover': config.colors?.light?.['error-hover'] ?? '#CD0000',
          '--vera-error-hover-light': config.colors?.light?.['error-hover'] ?? '#CD0000',
          '--vera-error-hover-dark': config.colors?.dark?.['error-hover'] ?? '#FE9696',
          '--vera-information': config.colors?.light?.['information'] ?? '#0276D5',
          '--vera-information-light': config.colors?.light?.['information'] ?? '#0276D5',
          '--vera-information-dark': config.colors?.dark?.['information'] ?? '#2997F0',
          '--vera-information-background':
            config.colors?.light?.['information-background'] ?? '#E8F4FB',
          '--vera-information-background-light':
            config.colors?.light?.['information-background'] ?? '#E8F4FB',
          '--vera-information-background-dark':
            config.colors?.dark?.['information-background'] ?? '#E8F4FB',
          '--vera-information-hover': config.colors?.light?.['information-hover'] ?? '#2997F0',
          '--vera-information-hover-light':
            config.colors?.light?.['information-hover'] ?? '#2997F0',
          '--vera-information-hover-dark': config.colors?.dark?.['information-hover'] ?? '#0276D5',
          '--vera-on-accent': config.colors?.light?.['on-accent'] ?? '#000000',
          '--vera-on-accent-light': config.colors?.light?.['on-accent'] ?? '#000000',
          '--vera-on-accent-dark': config.colors?.dark?.['on-accent'] ?? '#000000',
          '--vera-on-background': config.colors?.light?.['on-background'] ?? '#757575',
          '--vera-on-background-light': config.colors?.light?.['on-background'] ?? '#757575',
          '--vera-on-background-dark': config.colors?.dark?.['on-background'] ?? '#B3B3B3',
          '--vera-on-dark-grey': config.colors?.light?.['on-dark-grey'] ?? '#FFFFFF',
          '--vera-on-dark-grey-light': config.colors?.light?.['on-dark-grey'] ?? '#FFFFFF',
          '--vera-on-dark-grey-dark': config.colors?.dark?.['on-dark-grey'] ?? '#FFFFFF',
          '--vera-on-error': config.colors?.light?.['on-error'] ?? '#FFFFFF',
          '--vera-on-error-light': config.colors?.light?.['on-error'] ?? '#FFFFFF',
          '--vera-on-error-dark': config.colors?.dark?.['on-error'] ?? '#000000',
          '--vera-on-information': config.colors?.light?.['on-information'] ?? '#FFFFFF',
          '--vera-on-information-light': config.colors?.light?.['on-information'] ?? '#FFFFFF',
          '--vera-on-information-dark': config.colors?.dark?.['on-information'] ?? '#FFFFFF',
          '--vera-on-primary': config.colors?.light?.['on-primary'] ?? '#FFFFFF',
          '--vera-on-primary-light': config.colors?.light?.['on-primary'] ?? '#FFFFFF',
          '--vera-on-primary-dark': config.colors?.dark?.['on-primary'] ?? '#000000',
          '--vera-on-secondary': config.colors?.light?.['on-secondary'] ?? '#FFFFFF',
          '--vera-on-secondary-light': config.colors?.light?.['on-secondary'] ?? '#FFFFFF',
          '--vera-on-secondary-dark': config.colors?.dark?.['on-secondary'] ?? '#000000',
          '--vera-on-success': config.colors?.light?.['on-success'] ?? '#FFFFFF',
          '--vera-on-success-light': config.colors?.light?.['on-success'] ?? '#FFFFFF',
          '--vera-on-success-dark': config.colors?.dark?.['on-success'] ?? '#000000',
          '--vera-on-surface': config.colors?.light?.['on-surface'] ?? '#929292',
          '--vera-on-surface-light': config.colors?.light?.['on-surface'] ?? '#929292',
          '--vera-on-surface-dark': config.colors?.dark?.['on-surface'] ?? '#FFFFFF',
          '--vera-on-tertiary': config.colors?.light?.['on-tertiary'] ?? '#FFFFFF',
          '--vera-on-tertiary-light': config.colors?.light?.['on-tertiary'] ?? '#FFFFFF',
          '--vera-on-tertiary-dark': config.colors?.dark?.['on-tertiary'] ?? '#000000',
          '--vera-on-warning': config.colors?.light?.['on-warning'] ?? '#FFFFFF',
          '--vera-on-warning-light': config.colors?.light?.['on-warning'] ?? '#FFFFFF',
          '--vera-on-warning-dark': config.colors?.dark?.['on-warning'] ?? '#000000',
          '--vera-primary': config.colors?.light?.['primary'] ?? '#9941FF',
          '--vera-primary-light': config.colors?.light?.['primary'] ?? '#9941FF',
          '--vera-primary-dark': config.colors?.dark?.['primary'] ?? '#B27BF2',
          '--vera-primary-hover': config.colors?.light?.['primary-hover'] ?? '#871EFF',
          '--vera-primary-hover-light': config.colors?.light?.['primary-hover'] ?? '#871EFF',
          '--vera-primary-hover-dark': config.colors?.dark?.['primary-hover'] ?? '#CBA1FA',
          '--vera-secondary': config.colors?.light?.['secondary'] ?? '#000000',
          '--vera-secondary-light': config.colors?.light?.['secondary'] ?? '#000000',
          '--vera-secondary-dark': config.colors?.dark?.['secondary'] ?? '#FFFFFF',
          '--vera-secondary-hover': config.colors?.light?.['secondary-hover'] ?? '#666666',
          '--vera-secondary-hover-light': config.colors?.light?.['secondary-hover'] ?? '#666666',
          '--vera-secondary-hover-dark': config.colors?.dark?.['secondary-hover'] ?? '#929292',
          '--vera-skeleton-like': config.colors?.light?.['skeleton-like'] ?? '#B3B3B3',
          '--vera-skeleton-like-light': config.colors?.light?.['skeleton-like'] ?? '#B3B3B3',
          '--vera-skeleton-like-dark': config.colors?.dark?.['skeleton-like'] ?? '#333333',
          '--vera-success': config.colors?.light?.['success'] ?? '#1C8731',
          '--vera-success-light': config.colors?.light?.['success'] ?? '#1C8731',
          '--vera-success-dark': config.colors?.dark?.['success'] ?? '#30A849',
          '--vera-success-hover': config.colors?.light?.['success-hover'] ?? '#1F7629',
          '--vera-success-hover-light': config.colors?.light?.['success-hover'] ?? '#1F7629',
          '--vera-success-hover-dark': config.colors?.dark?.['success-hover'] ?? '#53CA6A',
          '--vera-surface': config.colors?.light?.['surface'] ?? '#FFFFFF',
          '--vera-surface-light': config.colors?.light?.['surface'] ?? '#FFFFFF',
          '--vera-surface-dark': config.colors?.dark?.['surface'] ?? '#000000',
          '--vera-tertiary': config.colors?.light?.['tertiary'] ?? '#757575',
          '--vera-tertiary-light': config.colors?.light?.['tertiary'] ?? '#757575',
          '--vera-tertiary-dark': config.colors?.dark?.['tertiary'] ?? '#B3B3B3',
          '--vera-tertiary-hover': config.colors?.light?.['tertiary-hover'] ?? '#929292',
          '--vera-tertiary-hover-light': config.colors?.light?.['tertiary-hover'] ?? '#929292',
          '--vera-tertiary-hover-dark': config.colors?.dark?.['tertiary-hover'] ?? '#B3B3B3',
          '--vera-text-disabled': config.colors?.light?.['text-disabled'] ?? '#B3B3B3',
          '--vera-text-disabled-light': config.colors?.light?.['text-disabled'] ?? '#B3B3B3',
          '--vera-text-disabled-dark': config.colors?.dark?.['text-disabled'] ?? '#666666',
          '--vera-text-primary': config.colors?.light?.['text-primary'] ?? '#9941FF',
          '--vera-text-primary-light': config.colors?.light?.['text-primary'] ?? '#9941FF',
          '--vera-text-primary-dark': config.colors?.dark?.['text-primary'] ?? '#B27BF2',
          '--vera-text-secondary': config.colors?.light?.['text-secondary'] ?? '#000000',
          '--vera-text-secondary-light': config.colors?.light?.['text-secondary'] ?? '#000000',
          '--vera-text-secondary-dark': config.colors?.dark?.['text-secondary'] ?? '#FFFFFF',
          '--vera-text-tertiary': config.colors?.light?.['text-tertiary'] ?? '#757575',
          '--vera-text-tertiary-light': config.colors?.light?.['text-tertiary'] ?? '#757575',
          '--vera-text-tertiary-dark': config.colors?.dark?.['text-tertiary'] ?? '#B3B3B3',
          '--vera-warning': config.colors?.light?.['warning'] ?? '#BE5702',
          '--vera-warning-light': config.colors?.light?.['warning'] ?? '#BE5702',
          '--vera-warning-dark': config.colors?.dark?.['warning'] ?? '#FA9F00',
          '--vera-warning-hover': config.colors?.light?.['warning-hover'] ?? '#A64C03',
          '--vera-warning-hover-light': config.colors?.light?.['warning-hover'] ?? '#A64C03',
          '--vera-warning-hover-dark': config.colors?.dark?.['warning-hover'] ?? '#FACC4B',

          // Typography and layout design tokens
          '--vera-border-radius-extra-large':
            config.borderRadius?.['extra-large'] != null
              ? config.borderRadius?.['extra-large'] + 'px'
              : '24px',
          '--vera-border-radius-extra-small':
            config.borderRadius?.['extra-small'] != null
              ? config.borderRadius?.['extra-small'] + 'px'
              : '2px',
          '--vera-border-radius-large':
            config.borderRadius?.['large'] != null ? config.borderRadius?.['large'] + 'px' : '12px',
          '--vera-border-radius-medium':
            config.borderRadius?.['medium'] != null
              ? config.borderRadius?.['medium'] + 'px'
              : '8px',
          '--vera-border-radius-none':
            config.borderRadius?.['none'] != null ? config.borderRadius?.['none'] + 'px' : '0px',
          '--vera-border-radius-small':
            config.borderRadius?.['small'] != null ? config.borderRadius?.['small'] + 'px' : '4px',
          '--vera-font-family-plain':
            config.typography?.['font-family'] ??
            'Inter, sans-serif, system-ui, ui-sans-serif, Marker Felt, Trebuchet MS',
          '--vera-typography-headline-font-size': config.typography?.['desktop']?.['headline']?.[
            'font-size'
          ]
            ? Number(config.typography?.['desktop']?.['headline']?.['font-size'].slice(0, -2)) /
                16 +
              'rem'
            : '4.125rem',
          '--vera-typography-headline-line-height': config.typography?.['desktop']?.['headline']?.[
            'line-height'
          ]
            ? Number(config.typography?.['desktop']?.['headline']?.['line-height'].slice(0, -2)) /
                16 +
              'rem'
            : '5.5rem',
          '--vera-typography-headline-font-weight':
            config.typography?.['desktop']?.['headline']?.['font-weight'] != null
              ? String(config.typography?.['desktop']?.['headline']?.['font-weight'])
              : '500',
          '--vera-typography-headline-mobile-font-size': config.typography?.['mobile']?.[
            'headline'
          ]?.['font-size']
            ? Number(config.typography?.['mobile']?.['headline']?.['font-size'].slice(0, -2)) / 16 +
              'rem'
            : '2rem',
          '--vera-typography-headline-mobile-line-height': config.typography?.['mobile']?.[
            'headline'
          ]?.['line-height']
            ? Number(config.typography?.['mobile']?.['headline']?.['line-height'].slice(0, -2)) /
                16 +
              'rem'
            : '2.5rem',
          '--vera-typography-headline-mobile-font-weight':
            config.typography?.['mobile']?.['headline']?.['font-weight'] != null
              ? String(config.typography?.['mobile']?.['headline']?.['font-weight'])
              : '500',
          '--vera-typography-subtitle-font-size': config.typography?.['desktop']?.['subtitle']?.[
            'font-size'
          ]
            ? Number(config.typography?.['desktop']?.['subtitle']?.['font-size'].slice(0, -2)) /
                16 +
              'rem'
            : '3.25rem',
          '--vera-typography-subtitle-line-height': config.typography?.['desktop']?.['subtitle']?.[
            'line-height'
          ]
            ? Number(config.typography?.['desktop']?.['subtitle']?.['line-height'].slice(0, -2)) /
                16 +
              'rem'
            : '4.25rem',
          '--vera-typography-subtitle-font-weight':
            config.typography?.['desktop']?.['subtitle']?.['font-weight'] != null
              ? String(config.typography?.['desktop']?.['subtitle']?.['font-weight'])
              : '500',
          '--vera-typography-subtitle-mobile-font-size': config.typography?.['mobile']?.[
            'subtitle'
          ]?.['font-size']
            ? Number(config.typography?.['mobile']?.['subtitle']?.['font-size'].slice(0, -2)) / 16 +
              'rem'
            : '1.875rem',
          '--vera-typography-subtitle-mobile-line-height': config.typography?.['mobile']?.[
            'subtitle'
          ]?.['line-height']
            ? Number(config.typography?.['mobile']?.['subtitle']?.['line-height'].slice(0, -2)) /
                16 +
              'rem'
            : '2.375rem',
          '--vera-typography-subtitle-mobile-font-weight':
            config.typography?.['mobile']?.['subtitle']?.['font-weight'] != null
              ? String(config.typography?.['mobile']?.['subtitle']?.['font-weight'])
              : '500',
          '--vera-typography-heading-1-font-size': config.typography?.['desktop']?.['heading-1']?.[
            'font-size'
          ]
            ? Number(config.typography?.['desktop']?.['heading-1']?.['font-size'].slice(0, -2)) /
                16 +
              'rem'
            : '2.5rem',
          '--vera-typography-heading-1-line-height': config.typography?.['desktop']?.[
            'heading-1'
          ]?.['line-height']
            ? Number(config.typography?.['desktop']?.['heading-1']?.['line-height'].slice(0, -2)) /
                16 +
              'rem'
            : '3.25rem',
          '--vera-typography-heading-1-font-weight':
            config.typography?.['desktop']?.['heading-1']?.['font-weight'] != null
              ? String(config.typography?.['desktop']?.['heading-1']?.['font-weight'])
              : '500',
          '--vera-typography-heading-1-mobile-font-size': config.typography?.['mobile']?.[
            'heading-1'
          ]?.['font-size']
            ? Number(config.typography?.['mobile']?.['heading-1']?.['font-size'].slice(0, -2)) /
                16 +
              'rem'
            : '1.75rem',
          '--vera-typography-heading-1-mobile-line-height': config.typography?.['mobile']?.[
            'heading-1'
          ]?.['line-height']
            ? Number(config.typography?.['mobile']?.['heading-1']?.['line-height'].slice(0, -2)) /
                16 +
              'rem'
            : '2.25rem',
          '--vera-typography-heading-1-mobile-font-weight':
            config.typography?.['mobile']?.['heading-1']?.['font-weight'] != null
              ? String(config.typography?.['mobile']?.['heading-1']?.['font-weight'])
              : '500',
          '--vera-typography-heading-2-font-size': config.typography?.['desktop']?.['heading-2']?.[
            'font-size'
          ]
            ? Number(config.typography?.['desktop']?.['heading-2']?.['font-size'].slice(0, -2)) /
                16 +
              'rem'
            : '2rem',
          '--vera-typography-heading-2-line-height': config.typography?.['desktop']?.[
            'heading-2'
          ]?.['line-height']
            ? Number(config.typography?.['desktop']?.['heading-2']?.['line-height'].slice(0, -2)) /
                16 +
              'rem'
            : '2.75rem',
          '--vera-typography-heading-2-font-weight':
            config.typography?.['desktop']?.['heading-2']?.['font-weight'] != null
              ? String(config.typography?.['desktop']?.['heading-2']?.['font-weight'])
              : '500',
          '--vera-typography-heading-2-mobile-font-size': config.typography?.['mobile']?.[
            'heading-2'
          ]?.['font-size']
            ? Number(config.typography?.['mobile']?.['heading-2']?.['font-size'].slice(0, -2)) /
                16 +
              'rem'
            : '1.5rem',
          '--vera-typography-heading-2-mobile-line-height': config.typography?.['mobile']?.[
            'heading-2'
          ]?.['line-height']
            ? Number(config.typography?.['mobile']?.['heading-2']?.['line-height'].slice(0, -2)) /
                16 +
              'rem'
            : '2rem',
          '--vera-typography-heading-2-mobile-font-weight':
            config.typography?.['mobile']?.['heading-2']?.['font-weight'] != null
              ? String(config.typography?.['mobile']?.['heading-2']?.['font-weight'])
              : '500',
          '--vera-typography-heading-3-font-size': config.typography?.['desktop']?.['heading-3']?.[
            'font-size'
          ]
            ? Number(config.typography?.['desktop']?.['heading-3']?.['font-size'].slice(0, -2)) /
                16 +
              'rem'
            : '1.625rem',
          '--vera-typography-heading-3-line-height': config.typography?.['desktop']?.[
            'heading-3'
          ]?.['line-height']
            ? Number(config.typography?.['desktop']?.['heading-3']?.['line-height'].slice(0, -2)) /
                16 +
              'rem'
            : '2.25rem',
          '--vera-typography-heading-3-font-weight':
            config.typography?.['desktop']?.['heading-3']?.['font-weight'] != null
              ? String(config.typography?.['desktop']?.['heading-3']?.['font-weight'])
              : '500',
          '--vera-typography-heading-3-mobile-font-size': config.typography?.['mobile']?.[
            'heading-3'
          ]?.['font-size']
            ? Number(config.typography?.['mobile']?.['heading-3']?.['font-size'].slice(0, -2)) /
                16 +
              'rem'
            : '1.25rem',
          '--vera-typography-heading-3-mobile-line-height': config.typography?.['mobile']?.[
            'heading-3'
          ]?.['line-height']
            ? Number(config.typography?.['mobile']?.['heading-3']?.['line-height'].slice(0, -2)) /
                16 +
              'rem'
            : '1.75rem',
          '--vera-typography-heading-3-mobile-font-weight':
            config.typography?.['mobile']?.['heading-3']?.['font-weight'] != null
              ? String(config.typography?.['mobile']?.['heading-3']?.['font-weight'])
              : '500',
          '--vera-typography-heading-4-font-size': config.typography?.['desktop']?.['heading-4']?.[
            'font-size'
          ]
            ? Number(config.typography?.['desktop']?.['heading-4']?.['font-size'].slice(0, -2)) /
                16 +
              'rem'
            : '1.25rem',
          '--vera-typography-heading-4-line-height': config.typography?.['desktop']?.[
            'heading-4'
          ]?.['line-height']
            ? Number(config.typography?.['desktop']?.['heading-4']?.['line-height'].slice(0, -2)) /
                16 +
              'rem'
            : '1.75rem',
          '--vera-typography-heading-4-font-weight':
            config.typography?.['desktop']?.['heading-4']?.['font-weight'] != null
              ? String(config.typography?.['desktop']?.['heading-4']?.['font-weight'])
              : '500',
          '--vera-typography-heading-4-mobile-font-size': config.typography?.['mobile']?.[
            'heading-4'
          ]?.['font-size']
            ? Number(config.typography?.['mobile']?.['heading-4']?.['font-size'].slice(0, -2)) /
                16 +
              'rem'
            : '1.125rem',
          '--vera-typography-heading-4-mobile-line-height': config.typography?.['mobile']?.[
            'heading-4'
          ]?.['line-height']
            ? Number(config.typography?.['mobile']?.['heading-4']?.['line-height'].slice(0, -2)) /
                16 +
              'rem'
            : '1.5rem',
          '--vera-typography-heading-4-mobile-font-weight':
            config.typography?.['mobile']?.['heading-4']?.['font-weight'] != null
              ? String(config.typography?.['mobile']?.['heading-4']?.['font-weight'])
              : '500',
          '--vera-typography-body-extended-font-size': config.typography?.['desktop']?.[
            'body-extended'
          ]?.['font-size']
            ? Number(
                config.typography?.['desktop']?.['body-extended']?.['font-size'].slice(0, -2)
              ) /
                16 +
              'rem'
            : '1rem',
          '--vera-typography-body-extended-line-height': config.typography?.['desktop']?.[
            'body-extended'
          ]?.['line-height']
            ? Number(
                config.typography?.['desktop']?.['body-extended']?.['line-height'].slice(0, -2)
              ) /
                16 +
              'rem'
            : '1.5rem',
          '--vera-typography-body-extended-font-weight':
            config.typography?.['desktop']?.['body-extended']?.['font-weight'] != null
              ? String(config.typography?.['desktop']?.['body-extended']?.['font-weight'])
              : '400',
          '--vera-typography-body-extended-mobile-font-size': config.typography?.['mobile']?.[
            'body-extended'
          ]?.['font-size']
            ? Number(config.typography?.['mobile']?.['body-extended']?.['font-size'].slice(0, -2)) /
                16 +
              'rem'
            : '1rem',
          '--vera-typography-body-extended-mobile-line-height': config.typography?.['mobile']?.[
            'body-extended'
          ]?.['line-height']
            ? Number(
                config.typography?.['mobile']?.['body-extended']?.['line-height'].slice(0, -2)
              ) /
                16 +
              'rem'
            : '1.5rem',
          '--vera-typography-body-extended-mobile-font-weight':
            config.typography?.['mobile']?.['body-extended']?.['font-weight'] != null
              ? String(config.typography?.['mobile']?.['body-extended']?.['font-weight'])
              : '400',
          '--vera-typography-body-extended-semibold-font-size': config.typography?.['desktop']?.[
            'body-extended-semibold'
          ]?.['font-size']
            ? Number(
                config.typography?.['desktop']?.['body-extended-semibold']?.['font-size'].slice(
                  0,
                  -2
                )
              ) /
                16 +
              'rem'
            : '1rem',
          '--vera-typography-body-extended-semibold-line-height': config.typography?.['desktop']?.[
            'body-extended-semibold'
          ]?.['line-height']
            ? Number(
                config.typography?.['desktop']?.['body-extended-semibold']?.['line-height'].slice(
                  0,
                  -2
                )
              ) /
                16 +
              'rem'
            : '1.5rem',
          '--vera-typography-body-extended-semibold-font-weight':
            config.typography?.['desktop']?.['body-extended-semibold']?.['font-weight'] != null
              ? String(config.typography?.['desktop']?.['body-extended-semibold']?.['font-weight'])
              : '600',
          '--vera-typography-body-extended-semibold-mobile-font-size': config.typography?.[
            'mobile'
          ]?.['body-extended-semibold']?.['font-size']
            ? Number(
                config.typography?.['mobile']?.['body-extended-semibold']?.['font-size'].slice(
                  0,
                  -2
                )
              ) /
                16 +
              'rem'
            : '1rem',
          '--vera-typography-body-extended-semibold-mobile-line-height': config.typography?.[
            'mobile'
          ]?.['body-extended-semibold']?.['line-height']
            ? Number(
                config.typography?.['mobile']?.['body-extended-semibold']?.['line-height'].slice(
                  0,
                  -2
                )
              ) /
                16 +
              'rem'
            : '1.5rem',
          '--vera-typography-body-extended-semibold-mobile-font-weight':
            config.typography?.['mobile']?.['body-extended-semibold']?.['font-weight'] != null
              ? String(config.typography?.['mobile']?.['body-extended-semibold']?.['font-weight'])
              : '600',
          '--vera-typography-body-base-font-size': config.typography?.['desktop']?.['body-base']?.[
            'font-size'
          ]
            ? Number(config.typography?.['desktop']?.['body-base']?.['font-size'].slice(0, -2)) /
                16 +
              'rem'
            : '0.875rem',
          '--vera-typography-body-base-line-height': config.typography?.['desktop']?.[
            'body-base'
          ]?.['line-height']
            ? Number(config.typography?.['desktop']?.['body-base']?.['line-height'].slice(0, -2)) /
                16 +
              'rem'
            : '1.25rem',
          '--vera-typography-body-base-font-weight':
            config.typography?.['desktop']?.['body-base']?.['font-weight'] != null
              ? String(config.typography?.['desktop']?.['body-base']?.['font-weight'])
              : '400',
          '--vera-typography-body-base-mobile-font-size': config.typography?.['mobile']?.[
            'body-base'
          ]?.['font-size']
            ? Number(config.typography?.['mobile']?.['body-base']?.['font-size'].slice(0, -2)) /
                16 +
              'rem'
            : '0.875rem',
          '--vera-typography-body-base-mobile-line-height': config.typography?.['mobile']?.[
            'body-base'
          ]?.['line-height']
            ? Number(config.typography?.['mobile']?.['body-base']?.['line-height'].slice(0, -2)) /
                16 +
              'rem'
            : '1.25rem',
          '--vera-typography-body-base-mobile-font-weight':
            config.typography?.['mobile']?.['body-base']?.['font-weight'] != null
              ? String(config.typography?.['mobile']?.['body-base']?.['font-weight'])
              : '400',
          '--vera-typography-body-base-semibold-font-size': config.typography?.['desktop']?.[
            'body-base-semibold'
          ]?.['font-size']
            ? Number(
                config.typography?.['desktop']?.['body-base-semibold']?.['font-size'].slice(0, -2)
              ) /
                16 +
              'rem'
            : '0.875rem',
          '--vera-typography-body-base-semibold-line-height': config.typography?.['desktop']?.[
            'body-base-semibold'
          ]?.['line-height']
            ? Number(
                config.typography?.['desktop']?.['body-base-semibold']?.['line-height'].slice(0, -2)
              ) /
                16 +
              'rem'
            : '1.25rem',
          '--vera-typography-body-base-semibold-font-weight':
            config.typography?.['desktop']?.['body-base-semibold']?.['font-weight'] != null
              ? String(config.typography?.['desktop']?.['body-base-semibold']?.['font-weight'])
              : '600',
          '--vera-typography-body-base-semibold-mobile-font-size': config.typography?.['mobile']?.[
            'body-base-semibold'
          ]?.['font-size']
            ? Number(
                config.typography?.['mobile']?.['body-base-semibold']?.['font-size'].slice(0, -2)
              ) /
                16 +
              'rem'
            : '0.875rem',
          '--vera-typography-body-base-semibold-mobile-line-height': config.typography?.[
            'mobile'
          ]?.['body-base-semibold']?.['line-height']
            ? Number(
                config.typography?.['mobile']?.['body-base-semibold']?.['line-height'].slice(0, -2)
              ) /
                16 +
              'rem'
            : '1.25rem',
          '--vera-typography-body-base-semibold-mobile-font-weight':
            config.typography?.['mobile']?.['body-base-semibold']?.['font-weight'] != null
              ? String(config.typography?.['mobile']?.['body-base-semibold']?.['font-weight'])
              : '600',
          '--vera-typography-caption-font-size': config.typography?.['desktop']?.['caption']?.[
            'font-size'
          ]
            ? Number(config.typography?.['desktop']?.['caption']?.['font-size'].slice(0, -2)) / 16 +
              'rem'
            : '0.75rem',
          '--vera-typography-caption-line-height': config.typography?.['desktop']?.['caption']?.[
            'line-height'
          ]
            ? Number(config.typography?.['desktop']?.['caption']?.['line-height'].slice(0, -2)) /
                16 +
              'rem'
            : '1rem',
          '--vera-typography-caption-font-weight':
            config.typography?.['desktop']?.['caption']?.['font-weight'] != null
              ? String(config.typography?.['desktop']?.['caption']?.['font-weight'])
              : '400',
          '--vera-typography-caption-mobile-font-size': config.typography?.['mobile']?.[
            'caption'
          ]?.['font-size']
            ? Number(config.typography?.['mobile']?.['caption']?.['font-size'].slice(0, -2)) / 16 +
              'rem'
            : '0.75rem',
          '--vera-typography-caption-mobile-line-height': config.typography?.['mobile']?.[
            'caption'
          ]?.['line-height']
            ? Number(config.typography?.['mobile']?.['caption']?.['line-height'].slice(0, -2)) /
                16 +
              'rem'
            : '1rem',
          '--vera-typography-caption-mobile-font-weight':
            config.typography?.['mobile']?.['caption']?.['font-weight'] != null
              ? String(config.typography?.['mobile']?.['caption']?.['font-weight'])
              : '400',
          '--vera-typography-caption-semibold-font-size': config.typography?.['desktop']?.[
            'caption-semibold'
          ]?.['font-size']
            ? Number(
                config.typography?.['desktop']?.['caption-semibold']?.['font-size'].slice(0, -2)
              ) /
                16 +
              'rem'
            : '0.75rem',
          '--vera-typography-caption-semibold-line-height': config.typography?.['desktop']?.[
            'caption-semibold'
          ]?.['line-height']
            ? Number(
                config.typography?.['desktop']?.['caption-semibold']?.['line-height'].slice(0, -2)
              ) /
                16 +
              'rem'
            : '1rem',
          '--vera-typography-caption-semibold-font-weight':
            config.typography?.['desktop']?.['caption-semibold']?.['font-weight'] != null
              ? String(config.typography?.['desktop']?.['caption-semibold']?.['font-weight'])
              : '600',
          '--vera-typography-caption-semibold-mobile-font-size': config.typography?.['mobile']?.[
            'caption-semibold'
          ]?.['font-size']
            ? Number(
                config.typography?.['mobile']?.['caption-semibold']?.['font-size'].slice(0, -2)
              ) /
                16 +
              'rem'
            : '0.75rem',
          '--vera-typography-caption-semibold-mobile-line-height': config.typography?.['mobile']?.[
            'caption-semibold'
          ]?.['line-height']
            ? Number(
                config.typography?.['mobile']?.['caption-semibold']?.['line-height'].slice(0, -2)
              ) /
                16 +
              'rem'
            : '1rem',
          '--vera-typography-caption-semibold-mobile-font-weight':
            config.typography?.['mobile']?.['caption-semibold']?.['font-weight'] != null
              ? String(config.typography?.['mobile']?.['caption-semibold']?.['font-weight'])
              : '600',
        },
        ':host(.vera-dark-mode), :host(.dark), html.vera-dark-mode': {
          '--vera-accent': config.colors?.dark?.['accent'] ?? '#FFFFFF',
          '--vera-alert-background': config.colors?.dark?.['alert-background'] ?? '#3E0004',
          '--vera-alert-background-hover':
            config.colors?.dark?.['alert-background-hover'] ?? '#6E0000',
          '--vera-alert-text': config.colors?.dark?.['alert-text'] ?? '#FEDFDF',
          '--vera-background': config.colors?.dark?.['background'] ?? '#26044D',
          '--vera-border': config.colors?.dark?.['border'] ?? '#333333',
          '--vera-dark-background': config.colors?.dark?.['dark-background'] ?? '#202124',
          '--vera-dark-grey': config.colors?.dark?.['dark-grey'] ?? '#333333',
          '--vera-dark-grey-hover': config.colors?.dark?.['dark-grey-hover'] ?? '#292828',
          '--vera-dark-grey-opacity': config.colors?.dark?.['dark-grey-opacity'] ?? '#333333CD',
          '--vera-disabled': config.colors?.dark?.['disabled'] ?? '#333333',
          '--vera-error': config.colors?.dark?.['error'] ?? '#F75959',
          '--vera-error-hover': config.colors?.dark?.['error-hover'] ?? '#FE9696',
          '--vera-information': config.colors?.dark?.['information'] ?? '#2997F0',
          '--vera-information-background':
            config.colors?.dark?.['information-background'] ?? '#E8F4FB',
          '--vera-information-hover': config.colors?.dark?.['information-hover'] ?? '#0276D5',
          '--vera-on-accent': config.colors?.dark?.['on-accent'] ?? '#000000',
          '--vera-on-background': config.colors?.dark?.['on-background'] ?? '#B3B3B3',
          '--vera-on-dark-grey': config.colors?.dark?.['on-dark-grey'] ?? '#FFFFFF',
          '--vera-on-error': config.colors?.dark?.['on-error'] ?? '#000000',
          '--vera-on-information': config.colors?.dark?.['on-information'] ?? '#FFFFFF',
          '--vera-on-primary': config.colors?.dark?.['on-primary'] ?? '#000000',
          '--vera-on-secondary': config.colors?.dark?.['on-secondary'] ?? '#000000',
          '--vera-on-success': config.colors?.dark?.['on-success'] ?? '#000000',
          '--vera-on-surface': config.colors?.dark?.['on-surface'] ?? '#FFFFFF',
          '--vera-on-tertiary': config.colors?.dark?.['on-tertiary'] ?? '#000000',
          '--vera-on-warning': config.colors?.dark?.['on-warning'] ?? '#000000',
          '--vera-primary': config.colors?.dark?.['primary'] ?? '#B27BF2',
          '--vera-primary-hover': config.colors?.dark?.['primary-hover'] ?? '#CBA1FA',
          '--vera-secondary': config.colors?.dark?.['secondary'] ?? '#FFFFFF',
          '--vera-secondary-hover': config.colors?.dark?.['secondary-hover'] ?? '#929292',
          '--vera-skeleton-like': config.colors?.dark?.['skeleton-like'] ?? '#333333',
          '--vera-success': config.colors?.dark?.['success'] ?? '#30A849',
          '--vera-success-hover': config.colors?.dark?.['success-hover'] ?? '#53CA6A',
          '--vera-surface': config.colors?.dark?.['surface'] ?? '#000000',
          '--vera-tertiary': config.colors?.dark?.['tertiary'] ?? '#B3B3B3',
          '--vera-tertiary-hover': config.colors?.dark?.['tertiary-hover'] ?? '#B3B3B3',
          '--vera-text-disabled': config.colors?.dark?.['text-disabled'] ?? '#666666',
          '--vera-text-primary': config.colors?.dark?.['text-primary'] ?? '#B27BF2',
          '--vera-text-secondary': config.colors?.dark?.['text-secondary'] ?? '#FFFFFF',
          '--vera-text-tertiary': config.colors?.dark?.['text-tertiary'] ?? '#B3B3B3',
          '--vera-warning': config.colors?.dark?.['warning'] ?? '#FA9F00',
          '--vera-warning-hover': config.colors?.dark?.['warning-hover'] ?? '#FACC4B',
        },
      });
      // headline
      fontSizeUtilities['.text-vera-headline'] = {
        fontSize: '2rem',
        lineHeight: '2.5rem',
        fontWeight: 500,
        '@media (min-width: 768px)': {
          fontSize: 'var(--vera-typography-headline-font-size, 4.125rem)',
          lineHeight: 'var(--vera-typography-headline-line-height, 5.5rem)',
          fontWeight: 'var(--vera-typography-headline-font-weight, 500)',
        },
      };

      fontWeightUtilities['.font-vera-headline'] = {
        fontWeight: 500,
        '@media (min-width: 768px)': {
          fontWeight: 'var(--vera-typography-headline-font-weight, 500)',
        },
      };

      // subtitle
      fontSizeUtilities['.text-vera-subtitle'] = {
        fontSize: '1.875rem',
        lineHeight: '2.375rem',
        fontWeight: 500,
        '@media (min-width: 768px)': {
          fontSize: 'var(--vera-typography-subtitle-font-size, 3.25rem)',
          lineHeight: 'var(--vera-typography-subtitle-line-height, 4.25rem)',
          fontWeight: 'var(--vera-typography-subtitle-font-weight, 500)',
        },
      };

      fontWeightUtilities['.font-vera-subtitle'] = {
        fontWeight: 500,
        '@media (min-width: 768px)': {
          fontWeight: 'var(--vera-typography-subtitle-font-weight, 500)',
        },
      };

      // heading-1
      fontSizeUtilities['.text-vera-heading-1'] = {
        fontSize: '1.75rem',
        lineHeight: '2.25rem',
        fontWeight: 500,
        '@media (min-width: 768px)': {
          fontSize: 'var(--vera-typography-heading-1-font-size, 2.5rem)',
          lineHeight: 'var(--vera-typography-heading-1-line-height, 3.25rem)',
          fontWeight: 'var(--vera-typography-heading-1-font-weight, 500)',
        },
      };

      fontWeightUtilities['.font-vera-heading-1'] = {
        fontWeight: 500,
        '@media (min-width: 768px)': {
          fontWeight: 'var(--vera-typography-heading-1-font-weight, 500)',
        },
      };

      // heading-2
      fontSizeUtilities['.text-vera-heading-2'] = {
        fontSize: '1.5rem',
        lineHeight: '2rem',
        fontWeight: 500,
        '@media (min-width: 768px)': {
          fontSize: 'var(--vera-typography-heading-2-font-size, 2rem)',
          lineHeight: 'var(--vera-typography-heading-2-line-height, 2.75rem)',
          fontWeight: 'var(--vera-typography-heading-2-font-weight, 500)',
        },
      };

      fontWeightUtilities['.font-vera-heading-2'] = {
        fontWeight: 500,
        '@media (min-width: 768px)': {
          fontWeight: 'var(--vera-typography-heading-2-font-weight, 500)',
        },
      };

      // heading-3
      fontSizeUtilities['.text-vera-heading-3'] = {
        fontSize: '1.25rem',
        lineHeight: '1.75rem',
        fontWeight: 500,
        '@media (min-width: 768px)': {
          fontSize: 'var(--vera-typography-heading-3-font-size, 1.625rem)',
          lineHeight: 'var(--vera-typography-heading-3-line-height, 2.25rem)',
          fontWeight: 'var(--vera-typography-heading-3-font-weight, 500)',
        },
      };

      fontWeightUtilities['.font-vera-heading-3'] = {
        fontWeight: 500,
        '@media (min-width: 768px)': {
          fontWeight: 'var(--vera-typography-heading-3-font-weight, 500)',
        },
      };

      // heading-4
      fontSizeUtilities['.text-vera-heading-4'] = {
        fontSize: '1.125rem',
        lineHeight: '1.5rem',
        fontWeight: 500,
        '@media (min-width: 768px)': {
          fontSize: 'var(--vera-typography-heading-4-font-size, 1.25rem)',
          lineHeight: 'var(--vera-typography-heading-4-line-height, 1.75rem)',
          fontWeight: 'var(--vera-typography-heading-4-font-weight, 500)',
        },
      };

      fontWeightUtilities['.font-vera-heading-4'] = {
        fontWeight: 500,
        '@media (min-width: 768px)': {
          fontWeight: 'var(--vera-typography-heading-4-font-weight, 500)',
        },
      };

      // body-extended
      fontSizeUtilities['.text-vera-body-extended'] = {
        fontSize: '1rem',
        lineHeight: '1.5rem',
        fontWeight: 400,
        '@media (min-width: 768px)': {
          fontSize: 'var(--vera-typography-body-extended-font-size, 1rem)',
          lineHeight: 'var(--vera-typography-body-extended-line-height, 1.5rem)',
          fontWeight: 'var(--vera-typography-body-extended-font-weight, 400)',
        },
      };

      fontWeightUtilities['.font-vera-body-extended'] = {
        fontWeight: 400,
        '@media (min-width: 768px)': {
          fontWeight: 'var(--vera-typography-body-extended-font-weight, 400)',
        },
      };

      // body-extended-semibold
      fontSizeUtilities['.text-vera-body-extended-semibold'] = {
        fontSize: '1rem',
        lineHeight: '1.5rem',
        fontWeight: 600,
        '@media (min-width: 768px)': {
          fontSize: 'var(--vera-typography-body-extended-semibold-font-size, 1rem)',
          lineHeight: 'var(--vera-typography-body-extended-semibold-line-height, 1.5rem)',
          fontWeight: 'var(--vera-typography-body-extended-semibold-font-weight, 600)',
        },
      };

      fontWeightUtilities['.font-vera-body-extended-semibold'] = {
        fontWeight: 600,
        '@media (min-width: 768px)': {
          fontWeight: 'var(--vera-typography-body-extended-semibold-font-weight, 600)',
        },
      };

      // body-base
      fontSizeUtilities['.text-vera-body-base'] = {
        fontSize: '0.875rem',
        lineHeight: '1.25rem',
        fontWeight: 400,
        '@media (min-width: 768px)': {
          fontSize: 'var(--vera-typography-body-base-font-size, 0.875rem)',
          lineHeight: 'var(--vera-typography-body-base-line-height, 1.25rem)',
          fontWeight: 'var(--vera-typography-body-base-font-weight, 400)',
        },
      };

      fontWeightUtilities['.font-vera-body-base'] = {
        fontWeight: 400,
        '@media (min-width: 768px)': {
          fontWeight: 'var(--vera-typography-body-base-font-weight, 400)',
        },
      };

      // body-base-semibold
      fontSizeUtilities['.text-vera-body-base-semibold'] = {
        fontSize: '0.875rem',
        lineHeight: '1.25rem',
        fontWeight: 600,
        '@media (min-width: 768px)': {
          fontSize: 'var(--vera-typography-body-base-semibold-font-size, 0.875rem)',
          lineHeight: 'var(--vera-typography-body-base-semibold-line-height, 1.25rem)',
          fontWeight: 'var(--vera-typography-body-base-semibold-font-weight, 600)',
        },
      };

      fontWeightUtilities['.font-vera-body-base-semibold'] = {
        fontWeight: 600,
        '@media (min-width: 768px)': {
          fontWeight: 'var(--vera-typography-body-base-semibold-font-weight, 600)',
        },
      };

      // caption
      fontSizeUtilities['.text-vera-caption'] = {
        fontSize: '0.75rem',
        lineHeight: '1rem',
        fontWeight: 400,
        '@media (min-width: 768px)': {
          fontSize: 'var(--vera-typography-caption-font-size, 0.75rem)',
          lineHeight: 'var(--vera-typography-caption-line-height, 1rem)',
          fontWeight: 'var(--vera-typography-caption-font-weight, 400)',
        },
      };

      fontWeightUtilities['.font-vera-caption'] = {
        fontWeight: 400,
        '@media (min-width: 768px)': {
          fontWeight: 'var(--vera-typography-caption-font-weight, 400)',
        },
      };

      // caption-semibold
      fontSizeUtilities['.text-vera-caption-semibold'] = {
        fontSize: '0.75rem',
        lineHeight: '1rem',
        fontWeight: 600,
        '@media (min-width: 768px)': {
          fontSize: 'var(--vera-typography-caption-semibold-font-size, 0.75rem)',
          lineHeight: 'var(--vera-typography-caption-semibold-line-height, 1rem)',
          fontWeight: 'var(--vera-typography-caption-semibold-font-weight, 600)',
        },
      };

      fontWeightUtilities['.font-vera-caption-semibold'] = {
        fontWeight: 600,
        '@media (min-width: 768px)': {
          fontWeight: 'var(--vera-typography-caption-semibold-font-weight, 600)',
        },
      };

      addUtilities(fontSizeUtilities);
      addUtilities(fontWeightUtilities);
    },
    {
      theme: {
        extend: {
          borderRadius: {
            'vera-extra-large': 'var(--vera-border-radius-extra-large, 24px)',
            'vera-extra-small': 'var(--vera-border-radius-extra-small, 2px)',
            'vera-large': 'var(--vera-border-radius-large, 12px)',
            'vera-medium': 'var(--vera-border-radius-medium, 8px)',
            'vera-none': 'var(--vera-border-radius-none, 0px)',
            'vera-small': 'var(--vera-border-radius-small, 4px)',
          },
          colors: {
            'vera-accent': 'var(--vera-accent, #FFFFFF)',
            'vera-accent-light': 'var(--vera-accent-light, #FFFFFF)',
            'vera-accent-dark': 'var(--vera-accent-dark, #FFFFFF)',
            'vera-alert-background': 'var(--vera-alert-background, #FFEEF2)',
            'vera-alert-background-light': 'var(--vera-alert-background-light, #FFEEF2)',
            'vera-alert-background-dark': 'var(--vera-alert-background-dark, #3E0004)',
            'vera-alert-background-hover': 'var(--vera-alert-background-hover, #FEDFDF)',
            'vera-alert-background-hover-light':
              'var(--vera-alert-background-hover-light, #FEDFDF)',
            'vera-alert-background-hover-dark': 'var(--vera-alert-background-hover-dark, #6E0000)',
            'vera-alert-text': 'var(--vera-alert-text, #CD0000)',
            'vera-alert-text-light': 'var(--vera-alert-text-light, #CD0000)',
            'vera-alert-text-dark': 'var(--vera-alert-text-dark, #FEDFDF)',
            'vera-background': 'var(--vera-background, #F5F0FD)',
            'vera-background-light': 'var(--vera-background-light, #F5F0FD)',
            'vera-background-dark': 'var(--vera-background-dark, #26044D)',
            'vera-border': 'var(--vera-border, #E6E6E6)',
            'vera-border-light': 'var(--vera-border-light, #E6E6E6)',
            'vera-border-dark': 'var(--vera-border-dark, #333333)',
            'vera-dark-background': 'var(--vera-dark-background, #202124)',
            'vera-dark-background-light': 'var(--vera-dark-background-light, #202124)',
            'vera-dark-background-dark': 'var(--vera-dark-background-dark, #202124)',
            'vera-dark-grey': 'var(--vera-dark-grey, #333333)',
            'vera-dark-grey-light': 'var(--vera-dark-grey-light, #333333)',
            'vera-dark-grey-dark': 'var(--vera-dark-grey-dark, #333333)',
            'vera-dark-grey-hover': 'var(--vera-dark-grey-hover, #292828)',
            'vera-dark-grey-hover-light': 'var(--vera-dark-grey-hover-light, #292828)',
            'vera-dark-grey-hover-dark': 'var(--vera-dark-grey-hover-dark, #292828)',
            'vera-dark-grey-opacity': 'var(--vera-dark-grey-opacity, #333333CD)',
            'vera-dark-grey-opacity-light': 'var(--vera-dark-grey-opacity-light, #333333CD)',
            'vera-dark-grey-opacity-dark': 'var(--vera-dark-grey-opacity-dark, #333333CD)',
            'vera-disabled': 'var(--vera-disabled, #E6E6E6)',
            'vera-disabled-light': 'var(--vera-disabled-light, #E6E6E6)',
            'vera-disabled-dark': 'var(--vera-disabled-dark, #333333)',
            'vera-error': 'var(--vera-error, #E61D1D)',
            'vera-error-light': 'var(--vera-error-light, #E61D1D)',
            'vera-error-dark': 'var(--vera-error-dark, #F75959)',
            'vera-error-hover': 'var(--vera-error-hover, #CD0000)',
            'vera-error-hover-light': 'var(--vera-error-hover-light, #CD0000)',
            'vera-error-hover-dark': 'var(--vera-error-hover-dark, #FE9696)',
            'vera-information': 'var(--vera-information, #0276D5)',
            'vera-information-light': 'var(--vera-information-light, #0276D5)',
            'vera-information-dark': 'var(--vera-information-dark, #2997F0)',
            'vera-information-background': 'var(--vera-information-background, #E8F4FB)',
            'vera-information-background-light':
              'var(--vera-information-background-light, #E8F4FB)',
            'vera-information-background-dark': 'var(--vera-information-background-dark, #E8F4FB)',
            'vera-information-hover': 'var(--vera-information-hover, #2997F0)',
            'vera-information-hover-light': 'var(--vera-information-hover-light, #2997F0)',
            'vera-information-hover-dark': 'var(--vera-information-hover-dark, #0276D5)',
            'vera-on-accent': 'var(--vera-on-accent, #000000)',
            'vera-on-accent-light': 'var(--vera-on-accent-light, #000000)',
            'vera-on-accent-dark': 'var(--vera-on-accent-dark, #000000)',
            'vera-on-background': 'var(--vera-on-background, #757575)',
            'vera-on-background-light': 'var(--vera-on-background-light, #757575)',
            'vera-on-background-dark': 'var(--vera-on-background-dark, #B3B3B3)',
            'vera-on-dark-grey': 'var(--vera-on-dark-grey, #FFFFFF)',
            'vera-on-dark-grey-light': 'var(--vera-on-dark-grey-light, #FFFFFF)',
            'vera-on-dark-grey-dark': 'var(--vera-on-dark-grey-dark, #FFFFFF)',
            'vera-on-error': 'var(--vera-on-error, #FFFFFF)',
            'vera-on-error-light': 'var(--vera-on-error-light, #FFFFFF)',
            'vera-on-error-dark': 'var(--vera-on-error-dark, #000000)',
            'vera-on-information': 'var(--vera-on-information, #FFFFFF)',
            'vera-on-information-light': 'var(--vera-on-information-light, #FFFFFF)',
            'vera-on-information-dark': 'var(--vera-on-information-dark, #FFFFFF)',
            'vera-on-primary': 'var(--vera-on-primary, #FFFFFF)',
            'vera-on-primary-light': 'var(--vera-on-primary-light, #FFFFFF)',
            'vera-on-primary-dark': 'var(--vera-on-primary-dark, #000000)',
            'vera-on-secondary': 'var(--vera-on-secondary, #FFFFFF)',
            'vera-on-secondary-light': 'var(--vera-on-secondary-light, #FFFFFF)',
            'vera-on-secondary-dark': 'var(--vera-on-secondary-dark, #000000)',
            'vera-on-success': 'var(--vera-on-success, #FFFFFF)',
            'vera-on-success-light': 'var(--vera-on-success-light, #FFFFFF)',
            'vera-on-success-dark': 'var(--vera-on-success-dark, #000000)',
            'vera-on-surface': 'var(--vera-on-surface, #929292)',
            'vera-on-surface-light': 'var(--vera-on-surface-light, #929292)',
            'vera-on-surface-dark': 'var(--vera-on-surface-dark, #FFFFFF)',
            'vera-on-tertiary': 'var(--vera-on-tertiary, #FFFFFF)',
            'vera-on-tertiary-light': 'var(--vera-on-tertiary-light, #FFFFFF)',
            'vera-on-tertiary-dark': 'var(--vera-on-tertiary-dark, #000000)',
            'vera-on-warning': 'var(--vera-on-warning, #FFFFFF)',
            'vera-on-warning-light': 'var(--vera-on-warning-light, #FFFFFF)',
            'vera-on-warning-dark': 'var(--vera-on-warning-dark, #000000)',
            'vera-primary': 'var(--vera-primary, #9941FF)',
            'vera-primary-light': 'var(--vera-primary-light, #9941FF)',
            'vera-primary-dark': 'var(--vera-primary-dark, #B27BF2)',
            'vera-primary-hover': 'var(--vera-primary-hover, #871EFF)',
            'vera-primary-hover-light': 'var(--vera-primary-hover-light, #871EFF)',
            'vera-primary-hover-dark': 'var(--vera-primary-hover-dark, #CBA1FA)',
            'vera-secondary': 'var(--vera-secondary, #000000)',
            'vera-secondary-light': 'var(--vera-secondary-light, #000000)',
            'vera-secondary-dark': 'var(--vera-secondary-dark, #FFFFFF)',
            'vera-secondary-hover': 'var(--vera-secondary-hover, #666666)',
            'vera-secondary-hover-light': 'var(--vera-secondary-hover-light, #666666)',
            'vera-secondary-hover-dark': 'var(--vera-secondary-hover-dark, #929292)',
            'vera-skeleton-like': 'var(--vera-skeleton-like, #B3B3B3)',
            'vera-skeleton-like-light': 'var(--vera-skeleton-like-light, #B3B3B3)',
            'vera-skeleton-like-dark': 'var(--vera-skeleton-like-dark, #333333)',
            'vera-success': 'var(--vera-success, #1C8731)',
            'vera-success-light': 'var(--vera-success-light, #1C8731)',
            'vera-success-dark': 'var(--vera-success-dark, #30A849)',
            'vera-success-hover': 'var(--vera-success-hover, #1F7629)',
            'vera-success-hover-light': 'var(--vera-success-hover-light, #1F7629)',
            'vera-success-hover-dark': 'var(--vera-success-hover-dark, #53CA6A)',
            'vera-surface': 'var(--vera-surface, #FFFFFF)',
            'vera-surface-light': 'var(--vera-surface-light, #FFFFFF)',
            'vera-surface-dark': 'var(--vera-surface-dark, #000000)',
            'vera-tertiary': 'var(--vera-tertiary, #757575)',
            'vera-tertiary-light': 'var(--vera-tertiary-light, #757575)',
            'vera-tertiary-dark': 'var(--vera-tertiary-dark, #B3B3B3)',
            'vera-tertiary-hover': 'var(--vera-tertiary-hover, #929292)',
            'vera-tertiary-hover-light': 'var(--vera-tertiary-hover-light, #929292)',
            'vera-tertiary-hover-dark': 'var(--vera-tertiary-hover-dark, #B3B3B3)',
            'vera-text-disabled': 'var(--vera-text-disabled, #B3B3B3)',
            'vera-text-disabled-light': 'var(--vera-text-disabled-light, #B3B3B3)',
            'vera-text-disabled-dark': 'var(--vera-text-disabled-dark, #666666)',
            'vera-text-primary': 'var(--vera-text-primary, #9941FF)',
            'vera-text-primary-light': 'var(--vera-text-primary-light, #9941FF)',
            'vera-text-primary-dark': 'var(--vera-text-primary-dark, #B27BF2)',
            'vera-text-secondary': 'var(--vera-text-secondary, #000000)',
            'vera-text-secondary-light': 'var(--vera-text-secondary-light, #000000)',
            'vera-text-secondary-dark': 'var(--vera-text-secondary-dark, #FFFFFF)',
            'vera-text-tertiary': 'var(--vera-text-tertiary, #757575)',
            'vera-text-tertiary-light': 'var(--vera-text-tertiary-light, #757575)',
            'vera-text-tertiary-dark': 'var(--vera-text-tertiary-dark, #B3B3B3)',
            'vera-warning': 'var(--vera-warning, #BE5702)',
            'vera-warning-light': 'var(--vera-warning-light, #BE5702)',
            'vera-warning-dark': 'var(--vera-warning-dark, #FA9F00)',
            'vera-warning-hover': 'var(--vera-warning-hover, #A64C03)',
            'vera-warning-hover-light': 'var(--vera-warning-hover-light, #A64C03)',
            'vera-warning-hover-dark': 'var(--vera-warning-hover-dark, #FACC4B)',
          },
          fontFamily: {
            'vera-plain': [
              'var(--vera-font-family-plain, Inter, sans-serif, system-ui, ui-sans-serif, Marker Felt, Trebuchet MS)',
            ],
          },
          screens: {
            'vera-mobile': {
              max: '767px',
            },
            'vera-desktop': {
              min: '768px',
            },
          },
        },
      },
    }
  );
};

veraUI.safelist = ['vera-dark-mode'];

module.exports = veraUI;
