/**
 * Auto-generated Tailwind plugin for Vera design system
 * DO NOT EDIT MANUALLY - Generated by generateTailwindPlugin.ts
 */
// eslint-disable-next-line @typescript-eslint/no-require-imports
const plugin = require('tailwindcss/plugin');

/**
 * Resolves a theme-aware color from the runtime config, falling back to the
 * value baked in from designTokens.json.
 */
const resolveColor = (config, mode, key, fallback) => config.colors?.[mode]?.[key] ?? fallback;

/**
 * Resolves a border radius token. Config values are plain numbers and get a
 * 'px' suffix; the fallback is already a full px string.
 */
const resolveBorderRadius = (config, key, fallback) => {
  const value = config.borderRadius?.[key];
  if (value == null) return fallback;
  return value + 'px';
};

/**
 * Resolves the plain font-family, falling back to the baked default.
 */
const resolveFontFamily = (config, fallback) => config.typography?.['font-family'] ?? fallback;

/**
 * Resolves a typography size (font-size / line-height). Config values are px
 * strings that get converted to rem; the fallback is already a rem string.
 */
const resolveTypographySize = (config, viewport, tokenKey, prop, fallback) => {
  const value = config.typography?.[viewport]?.[tokenKey]?.[prop];
  if (!value) return fallback;
  return Number(value.slice(0, -2)) / 16 + 'rem';
};

/**
 * Resolves a typography font-weight. Config values are numbers coerced to a
 * string; the fallback is already a string.
 */
const resolveTypographyWeight = (config, viewport, tokenKey, fallback) => {
  const value = config.typography?.[viewport]?.[tokenKey]?.['font-weight'];
  if (value == null) return fallback;
  return String(value);
};

/**
 * @param {import('../veraUI.types').VeraThemeTokens} [config] Optional theme
 * document (the same standardized designTokens.json shape). When provided, its
 * values override the baked-in defaults at runtime, which is what enables
 * live theme updates in dev without regenerating this file.
 */

const veraUI = (config = {}) => {
  return plugin(
    ({ addUtilities, addBase, addVariant }) => {
      const fontSizeUtilities = {};
      const fontWeightUtilities = {};

      // Add custom variants
      addVariant('child', '& > *');

      // Add CSS variables for theme-aware colors
      addBase({
        ':host, :root': {
          '--vera-accent': resolveColor(config, 'light', 'accent', '#FFFFFF'),
          '--vera-accent-light': resolveColor(config, 'light', 'accent', '#FFFFFF'),
          '--vera-accent-dark': resolveColor(config, 'dark', 'accent', '#FFFFFF'),
          '--vera-alert-background': resolveColor(config, 'light', 'alert-background', '#FFEEF2'),
          '--vera-alert-background-light': resolveColor(
            config,
            'light',
            'alert-background',
            '#FFEEF2'
          ),
          '--vera-alert-background-dark': resolveColor(
            config,
            'dark',
            'alert-background',
            '#3E0004'
          ),
          '--vera-alert-background-hover': resolveColor(
            config,
            'light',
            'alert-background-hover',
            '#FEDFDF'
          ),
          '--vera-alert-background-hover-light': resolveColor(
            config,
            'light',
            'alert-background-hover',
            '#FEDFDF'
          ),
          '--vera-alert-background-hover-dark': resolveColor(
            config,
            'dark',
            'alert-background-hover',
            '#6E0000'
          ),
          '--vera-alert-text': resolveColor(config, 'light', 'alert-text', '#CD0000'),
          '--vera-alert-text-light': resolveColor(config, 'light', 'alert-text', '#CD0000'),
          '--vera-alert-text-dark': resolveColor(config, 'dark', 'alert-text', '#FEDFDF'),
          '--vera-background': resolveColor(config, 'light', 'background', '#F5F0FD'),
          '--vera-background-light': resolveColor(config, 'light', 'background', '#F5F0FD'),
          '--vera-background-dark': resolveColor(config, 'dark', 'background', '#26044D'),
          '--vera-border': resolveColor(config, 'light', 'border', '#E6E6E6'),
          '--vera-border-light': resolveColor(config, 'light', 'border', '#E6E6E6'),
          '--vera-border-dark': resolveColor(config, 'dark', 'border', '#333333'),
          '--vera-dark-background': resolveColor(config, 'light', 'dark-background', '#202124'),
          '--vera-dark-background-light': resolveColor(
            config,
            'light',
            'dark-background',
            '#202124'
          ),
          '--vera-dark-background-dark': resolveColor(config, 'dark', 'dark-background', '#202124'),
          '--vera-dark-grey': resolveColor(config, 'light', 'dark-grey', '#333333'),
          '--vera-dark-grey-light': resolveColor(config, 'light', 'dark-grey', '#333333'),
          '--vera-dark-grey-dark': resolveColor(config, 'dark', 'dark-grey', '#333333'),
          '--vera-dark-grey-hover': resolveColor(config, 'light', 'dark-grey-hover', '#292828'),
          '--vera-dark-grey-hover-light': resolveColor(
            config,
            'light',
            'dark-grey-hover',
            '#292828'
          ),
          '--vera-dark-grey-hover-dark': resolveColor(config, 'dark', 'dark-grey-hover', '#292828'),
          '--vera-dark-grey-opacity': resolveColor(
            config,
            'light',
            'dark-grey-opacity',
            '#333333CD'
          ),
          '--vera-dark-grey-opacity-light': resolveColor(
            config,
            'light',
            'dark-grey-opacity',
            '#333333CD'
          ),
          '--vera-dark-grey-opacity-dark': resolveColor(
            config,
            'dark',
            'dark-grey-opacity',
            '#333333CD'
          ),
          '--vera-disabled': resolveColor(config, 'light', 'disabled', '#E6E6E6'),
          '--vera-disabled-light': resolveColor(config, 'light', 'disabled', '#E6E6E6'),
          '--vera-disabled-dark': resolveColor(config, 'dark', 'disabled', '#333333'),
          '--vera-error': resolveColor(config, 'light', 'error', '#E61D1D'),
          '--vera-error-light': resolveColor(config, 'light', 'error', '#E61D1D'),
          '--vera-error-dark': resolveColor(config, 'dark', 'error', '#F75959'),
          '--vera-error-hover': resolveColor(config, 'light', 'error-hover', '#CD0000'),
          '--vera-error-hover-light': resolveColor(config, 'light', 'error-hover', '#CD0000'),
          '--vera-error-hover-dark': resolveColor(config, 'dark', 'error-hover', '#FE9696'),
          '--vera-information': resolveColor(config, 'light', 'information', '#0276D5'),
          '--vera-information-light': resolveColor(config, 'light', 'information', '#0276D5'),
          '--vera-information-dark': resolveColor(config, 'dark', 'information', '#2997F0'),
          '--vera-information-background': resolveColor(
            config,
            'light',
            'information-background',
            '#E8F4FB'
          ),
          '--vera-information-background-light': resolveColor(
            config,
            'light',
            'information-background',
            '#E8F4FB'
          ),
          '--vera-information-background-dark': resolveColor(
            config,
            'dark',
            'information-background',
            '#E8F4FB'
          ),
          '--vera-information-hover': resolveColor(config, 'light', 'information-hover', '#2997F0'),
          '--vera-information-hover-light': resolveColor(
            config,
            'light',
            'information-hover',
            '#2997F0'
          ),
          '--vera-information-hover-dark': resolveColor(
            config,
            'dark',
            'information-hover',
            '#0276D5'
          ),
          '--vera-on-accent': resolveColor(config, 'light', 'on-accent', '#000000'),
          '--vera-on-accent-light': resolveColor(config, 'light', 'on-accent', '#000000'),
          '--vera-on-accent-dark': resolveColor(config, 'dark', 'on-accent', '#000000'),
          '--vera-on-background': resolveColor(config, 'light', 'on-background', '#757575'),
          '--vera-on-background-light': resolveColor(config, 'light', 'on-background', '#757575'),
          '--vera-on-background-dark': resolveColor(config, 'dark', 'on-background', '#B3B3B3'),
          '--vera-on-dark-grey': resolveColor(config, 'light', 'on-dark-grey', '#FFFFFF'),
          '--vera-on-dark-grey-light': resolveColor(config, 'light', 'on-dark-grey', '#FFFFFF'),
          '--vera-on-dark-grey-dark': resolveColor(config, 'dark', 'on-dark-grey', '#FFFFFF'),
          '--vera-on-error': resolveColor(config, 'light', 'on-error', '#FFFFFF'),
          '--vera-on-error-light': resolveColor(config, 'light', 'on-error', '#FFFFFF'),
          '--vera-on-error-dark': resolveColor(config, 'dark', 'on-error', '#000000'),
          '--vera-on-information': resolveColor(config, 'light', 'on-information', '#FFFFFF'),
          '--vera-on-information-light': resolveColor(config, 'light', 'on-information', '#FFFFFF'),
          '--vera-on-information-dark': resolveColor(config, 'dark', 'on-information', '#FFFFFF'),
          '--vera-on-primary': resolveColor(config, 'light', 'on-primary', '#FFFFFF'),
          '--vera-on-primary-light': resolveColor(config, 'light', 'on-primary', '#FFFFFF'),
          '--vera-on-primary-dark': resolveColor(config, 'dark', 'on-primary', '#000000'),
          '--vera-on-secondary': resolveColor(config, 'light', 'on-secondary', '#FFFFFF'),
          '--vera-on-secondary-light': resolveColor(config, 'light', 'on-secondary', '#FFFFFF'),
          '--vera-on-secondary-dark': resolveColor(config, 'dark', 'on-secondary', '#000000'),
          '--vera-on-success': resolveColor(config, 'light', 'on-success', '#FFFFFF'),
          '--vera-on-success-light': resolveColor(config, 'light', 'on-success', '#FFFFFF'),
          '--vera-on-success-dark': resolveColor(config, 'dark', 'on-success', '#000000'),
          '--vera-on-surface': resolveColor(config, 'light', 'on-surface', '#929292'),
          '--vera-on-surface-light': resolveColor(config, 'light', 'on-surface', '#929292'),
          '--vera-on-surface-dark': resolveColor(config, 'dark', 'on-surface', '#FFFFFF'),
          '--vera-on-tertiary': resolveColor(config, 'light', 'on-tertiary', '#FFFFFF'),
          '--vera-on-tertiary-light': resolveColor(config, 'light', 'on-tertiary', '#FFFFFF'),
          '--vera-on-tertiary-dark': resolveColor(config, 'dark', 'on-tertiary', '#000000'),
          '--vera-on-warning': resolveColor(config, 'light', 'on-warning', '#FFFFFF'),
          '--vera-on-warning-light': resolveColor(config, 'light', 'on-warning', '#FFFFFF'),
          '--vera-on-warning-dark': resolveColor(config, 'dark', 'on-warning', '#000000'),
          '--vera-primary': resolveColor(config, 'light', 'primary', '#9941FF'),
          '--vera-primary-light': resolveColor(config, 'light', 'primary', '#9941FF'),
          '--vera-primary-dark': resolveColor(config, 'dark', 'primary', '#B27BF2'),
          '--vera-primary-hover': resolveColor(config, 'light', 'primary-hover', '#871EFF'),
          '--vera-primary-hover-light': resolveColor(config, 'light', 'primary-hover', '#871EFF'),
          '--vera-primary-hover-dark': resolveColor(config, 'dark', 'primary-hover', '#CBA1FA'),
          '--vera-secondary': resolveColor(config, 'light', 'secondary', '#000000'),
          '--vera-secondary-light': resolveColor(config, 'light', 'secondary', '#000000'),
          '--vera-secondary-dark': resolveColor(config, 'dark', 'secondary', '#FFFFFF'),
          '--vera-secondary-hover': resolveColor(config, 'light', 'secondary-hover', '#666666'),
          '--vera-secondary-hover-light': resolveColor(
            config,
            'light',
            'secondary-hover',
            '#666666'
          ),
          '--vera-secondary-hover-dark': resolveColor(config, 'dark', 'secondary-hover', '#929292'),
          '--vera-skeleton-like': resolveColor(config, 'light', 'skeleton-like', '#B3B3B3'),
          '--vera-skeleton-like-light': resolveColor(config, 'light', 'skeleton-like', '#B3B3B3'),
          '--vera-skeleton-like-dark': resolveColor(config, 'dark', 'skeleton-like', '#333333'),
          '--vera-success': resolveColor(config, 'light', 'success', '#1C8731'),
          '--vera-success-light': resolveColor(config, 'light', 'success', '#1C8731'),
          '--vera-success-dark': resolveColor(config, 'dark', 'success', '#30A849'),
          '--vera-success-hover': resolveColor(config, 'light', 'success-hover', '#1F7629'),
          '--vera-success-hover-light': resolveColor(config, 'light', 'success-hover', '#1F7629'),
          '--vera-success-hover-dark': resolveColor(config, 'dark', 'success-hover', '#53CA6A'),
          '--vera-surface': resolveColor(config, 'light', 'surface', '#FFFFFF'),
          '--vera-surface-light': resolveColor(config, 'light', 'surface', '#FFFFFF'),
          '--vera-surface-dark': resolveColor(config, 'dark', 'surface', '#000000'),
          '--vera-tertiary': resolveColor(config, 'light', 'tertiary', '#757575'),
          '--vera-tertiary-light': resolveColor(config, 'light', 'tertiary', '#757575'),
          '--vera-tertiary-dark': resolveColor(config, 'dark', 'tertiary', '#B3B3B3'),
          '--vera-tertiary-hover': resolveColor(config, 'light', 'tertiary-hover', '#929292'),
          '--vera-tertiary-hover-light': resolveColor(config, 'light', 'tertiary-hover', '#929292'),
          '--vera-tertiary-hover-dark': resolveColor(config, 'dark', 'tertiary-hover', '#B3B3B3'),
          '--vera-text-disabled': resolveColor(config, 'light', 'text-disabled', '#B3B3B3'),
          '--vera-text-disabled-light': resolveColor(config, 'light', 'text-disabled', '#B3B3B3'),
          '--vera-text-disabled-dark': resolveColor(config, 'dark', 'text-disabled', '#666666'),
          '--vera-text-primary': resolveColor(config, 'light', 'text-primary', '#9941FF'),
          '--vera-text-primary-light': resolveColor(config, 'light', 'text-primary', '#9941FF'),
          '--vera-text-primary-dark': resolveColor(config, 'dark', 'text-primary', '#B27BF2'),
          '--vera-text-secondary': resolveColor(config, 'light', 'text-secondary', '#000000'),
          '--vera-text-secondary-light': resolveColor(config, 'light', 'text-secondary', '#000000'),
          '--vera-text-secondary-dark': resolveColor(config, 'dark', 'text-secondary', '#FFFFFF'),
          '--vera-text-tertiary': resolveColor(config, 'light', 'text-tertiary', '#757575'),
          '--vera-text-tertiary-light': resolveColor(config, 'light', 'text-tertiary', '#757575'),
          '--vera-text-tertiary-dark': resolveColor(config, 'dark', 'text-tertiary', '#B3B3B3'),
          '--vera-warning': resolveColor(config, 'light', 'warning', '#BE5702'),
          '--vera-warning-light': resolveColor(config, 'light', 'warning', '#BE5702'),
          '--vera-warning-dark': resolveColor(config, 'dark', 'warning', '#FA9F00'),
          '--vera-warning-hover': resolveColor(config, 'light', 'warning-hover', '#A64C03'),
          '--vera-warning-hover-light': resolveColor(config, 'light', 'warning-hover', '#A64C03'),
          '--vera-warning-hover-dark': resolveColor(config, 'dark', 'warning-hover', '#FACC4B'),

          // Typography and layout design tokens
          '--vera-border-radius-extra-large': resolveBorderRadius(config, 'extra-large', '24px'),
          '--vera-border-radius-extra-small': resolveBorderRadius(config, 'extra-small', '2px'),
          '--vera-border-radius-large': resolveBorderRadius(config, 'large', '12px'),
          '--vera-border-radius-medium': resolveBorderRadius(config, 'medium', '8px'),
          '--vera-border-radius-none': resolveBorderRadius(config, 'none', '0px'),
          '--vera-border-radius-small': resolveBorderRadius(config, 'small', '4px'),
          '--vera-font-family-plain': resolveFontFamily(
            config,
            'Inter, sans-serif, system-ui, ui-sans-serif, Marker Felt, Trebuchet MS'
          ),
          '--vera-typography-headline-font-size': resolveTypographySize(
            config,
            'desktop',
            'headline',
            'font-size',
            '4.125rem'
          ),
          '--vera-typography-headline-line-height': resolveTypographySize(
            config,
            'desktop',
            'headline',
            'line-height',
            '5.5rem'
          ),
          '--vera-typography-headline-font-weight': resolveTypographyWeight(
            config,
            'desktop',
            'headline',
            '500'
          ),
          '--vera-typography-headline-mobile-font-size': resolveTypographySize(
            config,
            'mobile',
            'headline',
            'font-size',
            '2rem'
          ),
          '--vera-typography-headline-mobile-line-height': resolveTypographySize(
            config,
            'mobile',
            'headline',
            'line-height',
            '2.5rem'
          ),
          '--vera-typography-headline-mobile-font-weight': resolveTypographyWeight(
            config,
            'mobile',
            'headline',
            '500'
          ),
          '--vera-typography-subtitle-font-size': resolveTypographySize(
            config,
            'desktop',
            'subtitle',
            'font-size',
            '3.25rem'
          ),
          '--vera-typography-subtitle-line-height': resolveTypographySize(
            config,
            'desktop',
            'subtitle',
            'line-height',
            '4.25rem'
          ),
          '--vera-typography-subtitle-font-weight': resolveTypographyWeight(
            config,
            'desktop',
            'subtitle',
            '500'
          ),
          '--vera-typography-subtitle-mobile-font-size': resolveTypographySize(
            config,
            'mobile',
            'subtitle',
            'font-size',
            '1.875rem'
          ),
          '--vera-typography-subtitle-mobile-line-height': resolveTypographySize(
            config,
            'mobile',
            'subtitle',
            'line-height',
            '2.375rem'
          ),
          '--vera-typography-subtitle-mobile-font-weight': resolveTypographyWeight(
            config,
            'mobile',
            'subtitle',
            '500'
          ),
          '--vera-typography-heading-1-font-size': resolveTypographySize(
            config,
            'desktop',
            'heading-1',
            'font-size',
            '2.5rem'
          ),
          '--vera-typography-heading-1-line-height': resolveTypographySize(
            config,
            'desktop',
            'heading-1',
            'line-height',
            '3.25rem'
          ),
          '--vera-typography-heading-1-font-weight': resolveTypographyWeight(
            config,
            'desktop',
            'heading-1',
            '500'
          ),
          '--vera-typography-heading-1-mobile-font-size': resolveTypographySize(
            config,
            'mobile',
            'heading-1',
            'font-size',
            '1.75rem'
          ),
          '--vera-typography-heading-1-mobile-line-height': resolveTypographySize(
            config,
            'mobile',
            'heading-1',
            'line-height',
            '2.25rem'
          ),
          '--vera-typography-heading-1-mobile-font-weight': resolveTypographyWeight(
            config,
            'mobile',
            'heading-1',
            '500'
          ),
          '--vera-typography-heading-2-font-size': resolveTypographySize(
            config,
            'desktop',
            'heading-2',
            'font-size',
            '2rem'
          ),
          '--vera-typography-heading-2-line-height': resolveTypographySize(
            config,
            'desktop',
            'heading-2',
            'line-height',
            '2.75rem'
          ),
          '--vera-typography-heading-2-font-weight': resolveTypographyWeight(
            config,
            'desktop',
            'heading-2',
            '500'
          ),
          '--vera-typography-heading-2-mobile-font-size': resolveTypographySize(
            config,
            'mobile',
            'heading-2',
            'font-size',
            '1.5rem'
          ),
          '--vera-typography-heading-2-mobile-line-height': resolveTypographySize(
            config,
            'mobile',
            'heading-2',
            'line-height',
            '2rem'
          ),
          '--vera-typography-heading-2-mobile-font-weight': resolveTypographyWeight(
            config,
            'mobile',
            'heading-2',
            '500'
          ),
          '--vera-typography-heading-3-font-size': resolveTypographySize(
            config,
            'desktop',
            'heading-3',
            'font-size',
            '1.625rem'
          ),
          '--vera-typography-heading-3-line-height': resolveTypographySize(
            config,
            'desktop',
            'heading-3',
            'line-height',
            '2.25rem'
          ),
          '--vera-typography-heading-3-font-weight': resolveTypographyWeight(
            config,
            'desktop',
            'heading-3',
            '500'
          ),
          '--vera-typography-heading-3-mobile-font-size': resolveTypographySize(
            config,
            'mobile',
            'heading-3',
            'font-size',
            '1.25rem'
          ),
          '--vera-typography-heading-3-mobile-line-height': resolveTypographySize(
            config,
            'mobile',
            'heading-3',
            'line-height',
            '1.75rem'
          ),
          '--vera-typography-heading-3-mobile-font-weight': resolveTypographyWeight(
            config,
            'mobile',
            'heading-3',
            '500'
          ),
          '--vera-typography-heading-4-font-size': resolveTypographySize(
            config,
            'desktop',
            'heading-4',
            'font-size',
            '1.25rem'
          ),
          '--vera-typography-heading-4-line-height': resolveTypographySize(
            config,
            'desktop',
            'heading-4',
            'line-height',
            '1.75rem'
          ),
          '--vera-typography-heading-4-font-weight': resolveTypographyWeight(
            config,
            'desktop',
            'heading-4',
            '500'
          ),
          '--vera-typography-heading-4-mobile-font-size': resolveTypographySize(
            config,
            'mobile',
            'heading-4',
            'font-size',
            '1.125rem'
          ),
          '--vera-typography-heading-4-mobile-line-height': resolveTypographySize(
            config,
            'mobile',
            'heading-4',
            'line-height',
            '1.5rem'
          ),
          '--vera-typography-heading-4-mobile-font-weight': resolveTypographyWeight(
            config,
            'mobile',
            'heading-4',
            '500'
          ),
          '--vera-typography-body-extended-font-size': resolveTypographySize(
            config,
            'desktop',
            'body-extended',
            'font-size',
            '1rem'
          ),
          '--vera-typography-body-extended-line-height': resolveTypographySize(
            config,
            'desktop',
            'body-extended',
            'line-height',
            '1.5rem'
          ),
          '--vera-typography-body-extended-font-weight': resolveTypographyWeight(
            config,
            'desktop',
            'body-extended',
            '400'
          ),
          '--vera-typography-body-extended-mobile-font-size': resolveTypographySize(
            config,
            'mobile',
            'body-extended',
            'font-size',
            '1rem'
          ),
          '--vera-typography-body-extended-mobile-line-height': resolveTypographySize(
            config,
            'mobile',
            'body-extended',
            'line-height',
            '1.5rem'
          ),
          '--vera-typography-body-extended-mobile-font-weight': resolveTypographyWeight(
            config,
            'mobile',
            'body-extended',
            '400'
          ),
          '--vera-typography-body-extended-semibold-font-size': resolveTypographySize(
            config,
            'desktop',
            'body-extended-semibold',
            'font-size',
            '1rem'
          ),
          '--vera-typography-body-extended-semibold-line-height': resolveTypographySize(
            config,
            'desktop',
            'body-extended-semibold',
            'line-height',
            '1.5rem'
          ),
          '--vera-typography-body-extended-semibold-font-weight': resolveTypographyWeight(
            config,
            'desktop',
            'body-extended-semibold',
            '600'
          ),
          '--vera-typography-body-extended-semibold-mobile-font-size': resolveTypographySize(
            config,
            'mobile',
            'body-extended-semibold',
            'font-size',
            '1rem'
          ),
          '--vera-typography-body-extended-semibold-mobile-line-height': resolveTypographySize(
            config,
            'mobile',
            'body-extended-semibold',
            'line-height',
            '1.5rem'
          ),
          '--vera-typography-body-extended-semibold-mobile-font-weight': resolveTypographyWeight(
            config,
            'mobile',
            'body-extended-semibold',
            '600'
          ),
          '--vera-typography-body-base-font-size': resolveTypographySize(
            config,
            'desktop',
            'body-base',
            'font-size',
            '0.875rem'
          ),
          '--vera-typography-body-base-line-height': resolveTypographySize(
            config,
            'desktop',
            'body-base',
            'line-height',
            '1.25rem'
          ),
          '--vera-typography-body-base-font-weight': resolveTypographyWeight(
            config,
            'desktop',
            'body-base',
            '400'
          ),
          '--vera-typography-body-base-mobile-font-size': resolveTypographySize(
            config,
            'mobile',
            'body-base',
            'font-size',
            '0.875rem'
          ),
          '--vera-typography-body-base-mobile-line-height': resolveTypographySize(
            config,
            'mobile',
            'body-base',
            'line-height',
            '1.25rem'
          ),
          '--vera-typography-body-base-mobile-font-weight': resolveTypographyWeight(
            config,
            'mobile',
            'body-base',
            '400'
          ),
          '--vera-typography-body-base-semibold-font-size': resolveTypographySize(
            config,
            'desktop',
            'body-base-semibold',
            'font-size',
            '0.875rem'
          ),
          '--vera-typography-body-base-semibold-line-height': resolveTypographySize(
            config,
            'desktop',
            'body-base-semibold',
            'line-height',
            '1.25rem'
          ),
          '--vera-typography-body-base-semibold-font-weight': resolveTypographyWeight(
            config,
            'desktop',
            'body-base-semibold',
            '600'
          ),
          '--vera-typography-body-base-semibold-mobile-font-size': resolveTypographySize(
            config,
            'mobile',
            'body-base-semibold',
            'font-size',
            '0.875rem'
          ),
          '--vera-typography-body-base-semibold-mobile-line-height': resolveTypographySize(
            config,
            'mobile',
            'body-base-semibold',
            'line-height',
            '1.25rem'
          ),
          '--vera-typography-body-base-semibold-mobile-font-weight': resolveTypographyWeight(
            config,
            'mobile',
            'body-base-semibold',
            '600'
          ),
          '--vera-typography-caption-font-size': resolveTypographySize(
            config,
            'desktop',
            'caption',
            'font-size',
            '0.75rem'
          ),
          '--vera-typography-caption-line-height': resolveTypographySize(
            config,
            'desktop',
            'caption',
            'line-height',
            '1rem'
          ),
          '--vera-typography-caption-font-weight': resolveTypographyWeight(
            config,
            'desktop',
            'caption',
            '400'
          ),
          '--vera-typography-caption-mobile-font-size': resolveTypographySize(
            config,
            'mobile',
            'caption',
            'font-size',
            '0.75rem'
          ),
          '--vera-typography-caption-mobile-line-height': resolveTypographySize(
            config,
            'mobile',
            'caption',
            'line-height',
            '1rem'
          ),
          '--vera-typography-caption-mobile-font-weight': resolveTypographyWeight(
            config,
            'mobile',
            'caption',
            '400'
          ),
          '--vera-typography-caption-semibold-font-size': resolveTypographySize(
            config,
            'desktop',
            'caption-semibold',
            'font-size',
            '0.75rem'
          ),
          '--vera-typography-caption-semibold-line-height': resolveTypographySize(
            config,
            'desktop',
            'caption-semibold',
            'line-height',
            '1rem'
          ),
          '--vera-typography-caption-semibold-font-weight': resolveTypographyWeight(
            config,
            'desktop',
            'caption-semibold',
            '600'
          ),
          '--vera-typography-caption-semibold-mobile-font-size': resolveTypographySize(
            config,
            'mobile',
            'caption-semibold',
            'font-size',
            '0.75rem'
          ),
          '--vera-typography-caption-semibold-mobile-line-height': resolveTypographySize(
            config,
            'mobile',
            'caption-semibold',
            'line-height',
            '1rem'
          ),
          '--vera-typography-caption-semibold-mobile-font-weight': resolveTypographyWeight(
            config,
            'mobile',
            'caption-semibold',
            '600'
          ),
        },
        ':host(.vera-dark-mode), :host(.dark), html.vera-dark-mode': {
          '--vera-accent': resolveColor(config, 'dark', 'accent', '#FFFFFF'),
          '--vera-alert-background': resolveColor(config, 'dark', 'alert-background', '#3E0004'),
          '--vera-alert-background-hover': resolveColor(
            config,
            'dark',
            'alert-background-hover',
            '#6E0000'
          ),
          '--vera-alert-text': resolveColor(config, 'dark', 'alert-text', '#FEDFDF'),
          '--vera-background': resolveColor(config, 'dark', 'background', '#26044D'),
          '--vera-border': resolveColor(config, 'dark', 'border', '#333333'),
          '--vera-dark-background': resolveColor(config, 'dark', 'dark-background', '#202124'),
          '--vera-dark-grey': resolveColor(config, 'dark', 'dark-grey', '#333333'),
          '--vera-dark-grey-hover': resolveColor(config, 'dark', 'dark-grey-hover', '#292828'),
          '--vera-dark-grey-opacity': resolveColor(
            config,
            'dark',
            'dark-grey-opacity',
            '#333333CD'
          ),
          '--vera-disabled': resolveColor(config, 'dark', 'disabled', '#333333'),
          '--vera-error': resolveColor(config, 'dark', 'error', '#F75959'),
          '--vera-error-hover': resolveColor(config, 'dark', 'error-hover', '#FE9696'),
          '--vera-information': resolveColor(config, 'dark', 'information', '#2997F0'),
          '--vera-information-background': resolveColor(
            config,
            'dark',
            'information-background',
            '#E8F4FB'
          ),
          '--vera-information-hover': resolveColor(config, 'dark', 'information-hover', '#0276D5'),
          '--vera-on-accent': resolveColor(config, 'dark', 'on-accent', '#000000'),
          '--vera-on-background': resolveColor(config, 'dark', 'on-background', '#B3B3B3'),
          '--vera-on-dark-grey': resolveColor(config, 'dark', 'on-dark-grey', '#FFFFFF'),
          '--vera-on-error': resolveColor(config, 'dark', 'on-error', '#000000'),
          '--vera-on-information': resolveColor(config, 'dark', 'on-information', '#FFFFFF'),
          '--vera-on-primary': resolveColor(config, 'dark', 'on-primary', '#000000'),
          '--vera-on-secondary': resolveColor(config, 'dark', 'on-secondary', '#000000'),
          '--vera-on-success': resolveColor(config, 'dark', 'on-success', '#000000'),
          '--vera-on-surface': resolveColor(config, 'dark', 'on-surface', '#FFFFFF'),
          '--vera-on-tertiary': resolveColor(config, 'dark', 'on-tertiary', '#000000'),
          '--vera-on-warning': resolveColor(config, 'dark', 'on-warning', '#000000'),
          '--vera-primary': resolveColor(config, 'dark', 'primary', '#B27BF2'),
          '--vera-primary-hover': resolveColor(config, 'dark', 'primary-hover', '#CBA1FA'),
          '--vera-secondary': resolveColor(config, 'dark', 'secondary', '#FFFFFF'),
          '--vera-secondary-hover': resolveColor(config, 'dark', 'secondary-hover', '#929292'),
          '--vera-skeleton-like': resolveColor(config, 'dark', 'skeleton-like', '#333333'),
          '--vera-success': resolveColor(config, 'dark', 'success', '#30A849'),
          '--vera-success-hover': resolveColor(config, 'dark', 'success-hover', '#53CA6A'),
          '--vera-surface': resolveColor(config, 'dark', 'surface', '#000000'),
          '--vera-tertiary': resolveColor(config, 'dark', 'tertiary', '#B3B3B3'),
          '--vera-tertiary-hover': resolveColor(config, 'dark', 'tertiary-hover', '#B3B3B3'),
          '--vera-text-disabled': resolveColor(config, 'dark', 'text-disabled', '#666666'),
          '--vera-text-primary': resolveColor(config, 'dark', 'text-primary', '#B27BF2'),
          '--vera-text-secondary': resolveColor(config, 'dark', 'text-secondary', '#FFFFFF'),
          '--vera-text-tertiary': resolveColor(config, 'dark', 'text-tertiary', '#B3B3B3'),
          '--vera-warning': resolveColor(config, 'dark', 'warning', '#FA9F00'),
          '--vera-warning-hover': resolveColor(config, 'dark', 'warning-hover', '#FACC4B'),
        },
      });
      // headline
      fontSizeUtilities['.text-vera-headline'] = {
        fontSize: '2rem',
        lineHeight: '2.5rem',
        fontWeight: 500,
        '@media (min-width: 768px)': {
          fontSize: 'var(--vera-typography-headline-font-size, 4.125rem)',
          lineHeight: 'var(--vera-typography-headline-line-height, 5.5rem)',
          fontWeight: 'var(--vera-typography-headline-font-weight, 500)',
        },
      };

      fontWeightUtilities['.font-vera-headline'] = {
        fontWeight: 500,
        '@media (min-width: 768px)': {
          fontWeight: 'var(--vera-typography-headline-font-weight, 500)',
        },
      };

      // subtitle
      fontSizeUtilities['.text-vera-subtitle'] = {
        fontSize: '1.875rem',
        lineHeight: '2.375rem',
        fontWeight: 500,
        '@media (min-width: 768px)': {
          fontSize: 'var(--vera-typography-subtitle-font-size, 3.25rem)',
          lineHeight: 'var(--vera-typography-subtitle-line-height, 4.25rem)',
          fontWeight: 'var(--vera-typography-subtitle-font-weight, 500)',
        },
      };

      fontWeightUtilities['.font-vera-subtitle'] = {
        fontWeight: 500,
        '@media (min-width: 768px)': {
          fontWeight: 'var(--vera-typography-subtitle-font-weight, 500)',
        },
      };

      // heading-1
      fontSizeUtilities['.text-vera-heading-1'] = {
        fontSize: '1.75rem',
        lineHeight: '2.25rem',
        fontWeight: 500,
        '@media (min-width: 768px)': {
          fontSize: 'var(--vera-typography-heading-1-font-size, 2.5rem)',
          lineHeight: 'var(--vera-typography-heading-1-line-height, 3.25rem)',
          fontWeight: 'var(--vera-typography-heading-1-font-weight, 500)',
        },
      };

      fontWeightUtilities['.font-vera-heading-1'] = {
        fontWeight: 500,
        '@media (min-width: 768px)': {
          fontWeight: 'var(--vera-typography-heading-1-font-weight, 500)',
        },
      };

      // heading-2
      fontSizeUtilities['.text-vera-heading-2'] = {
        fontSize: '1.5rem',
        lineHeight: '2rem',
        fontWeight: 500,
        '@media (min-width: 768px)': {
          fontSize: 'var(--vera-typography-heading-2-font-size, 2rem)',
          lineHeight: 'var(--vera-typography-heading-2-line-height, 2.75rem)',
          fontWeight: 'var(--vera-typography-heading-2-font-weight, 500)',
        },
      };

      fontWeightUtilities['.font-vera-heading-2'] = {
        fontWeight: 500,
        '@media (min-width: 768px)': {
          fontWeight: 'var(--vera-typography-heading-2-font-weight, 500)',
        },
      };

      // heading-3
      fontSizeUtilities['.text-vera-heading-3'] = {
        fontSize: '1.25rem',
        lineHeight: '1.75rem',
        fontWeight: 500,
        '@media (min-width: 768px)': {
          fontSize: 'var(--vera-typography-heading-3-font-size, 1.625rem)',
          lineHeight: 'var(--vera-typography-heading-3-line-height, 2.25rem)',
          fontWeight: 'var(--vera-typography-heading-3-font-weight, 500)',
        },
      };

      fontWeightUtilities['.font-vera-heading-3'] = {
        fontWeight: 500,
        '@media (min-width: 768px)': {
          fontWeight: 'var(--vera-typography-heading-3-font-weight, 500)',
        },
      };

      // heading-4
      fontSizeUtilities['.text-vera-heading-4'] = {
        fontSize: '1.125rem',
        lineHeight: '1.5rem',
        fontWeight: 500,
        '@media (min-width: 768px)': {
          fontSize: 'var(--vera-typography-heading-4-font-size, 1.25rem)',
          lineHeight: 'var(--vera-typography-heading-4-line-height, 1.75rem)',
          fontWeight: 'var(--vera-typography-heading-4-font-weight, 500)',
        },
      };

      fontWeightUtilities['.font-vera-heading-4'] = {
        fontWeight: 500,
        '@media (min-width: 768px)': {
          fontWeight: 'var(--vera-typography-heading-4-font-weight, 500)',
        },
      };

      // body-extended
      fontSizeUtilities['.text-vera-body-extended'] = {
        fontSize: '1rem',
        lineHeight: '1.5rem',
        fontWeight: 400,
        '@media (min-width: 768px)': {
          fontSize: 'var(--vera-typography-body-extended-font-size, 1rem)',
          lineHeight: 'var(--vera-typography-body-extended-line-height, 1.5rem)',
          fontWeight: 'var(--vera-typography-body-extended-font-weight, 400)',
        },
      };

      fontWeightUtilities['.font-vera-body-extended'] = {
        fontWeight: 400,
        '@media (min-width: 768px)': {
          fontWeight: 'var(--vera-typography-body-extended-font-weight, 400)',
        },
      };

      // body-extended-semibold
      fontSizeUtilities['.text-vera-body-extended-semibold'] = {
        fontSize: '1rem',
        lineHeight: '1.5rem',
        fontWeight: 600,
        '@media (min-width: 768px)': {
          fontSize: 'var(--vera-typography-body-extended-semibold-font-size, 1rem)',
          lineHeight: 'var(--vera-typography-body-extended-semibold-line-height, 1.5rem)',
          fontWeight: 'var(--vera-typography-body-extended-semibold-font-weight, 600)',
        },
      };

      fontWeightUtilities['.font-vera-body-extended-semibold'] = {
        fontWeight: 600,
        '@media (min-width: 768px)': {
          fontWeight: 'var(--vera-typography-body-extended-semibold-font-weight, 600)',
        },
      };

      // body-base
      fontSizeUtilities['.text-vera-body-base'] = {
        fontSize: '0.875rem',
        lineHeight: '1.25rem',
        fontWeight: 400,
        '@media (min-width: 768px)': {
          fontSize: 'var(--vera-typography-body-base-font-size, 0.875rem)',
          lineHeight: 'var(--vera-typography-body-base-line-height, 1.25rem)',
          fontWeight: 'var(--vera-typography-body-base-font-weight, 400)',
        },
      };

      fontWeightUtilities['.font-vera-body-base'] = {
        fontWeight: 400,
        '@media (min-width: 768px)': {
          fontWeight: 'var(--vera-typography-body-base-font-weight, 400)',
        },
      };

      // body-base-semibold
      fontSizeUtilities['.text-vera-body-base-semibold'] = {
        fontSize: '0.875rem',
        lineHeight: '1.25rem',
        fontWeight: 600,
        '@media (min-width: 768px)': {
          fontSize: 'var(--vera-typography-body-base-semibold-font-size, 0.875rem)',
          lineHeight: 'var(--vera-typography-body-base-semibold-line-height, 1.25rem)',
          fontWeight: 'var(--vera-typography-body-base-semibold-font-weight, 600)',
        },
      };

      fontWeightUtilities['.font-vera-body-base-semibold'] = {
        fontWeight: 600,
        '@media (min-width: 768px)': {
          fontWeight: 'var(--vera-typography-body-base-semibold-font-weight, 600)',
        },
      };

      // caption
      fontSizeUtilities['.text-vera-caption'] = {
        fontSize: '0.75rem',
        lineHeight: '1rem',
        fontWeight: 400,
        '@media (min-width: 768px)': {
          fontSize: 'var(--vera-typography-caption-font-size, 0.75rem)',
          lineHeight: 'var(--vera-typography-caption-line-height, 1rem)',
          fontWeight: 'var(--vera-typography-caption-font-weight, 400)',
        },
      };

      fontWeightUtilities['.font-vera-caption'] = {
        fontWeight: 400,
        '@media (min-width: 768px)': {
          fontWeight: 'var(--vera-typography-caption-font-weight, 400)',
        },
      };

      // caption-semibold
      fontSizeUtilities['.text-vera-caption-semibold'] = {
        fontSize: '0.75rem',
        lineHeight: '1rem',
        fontWeight: 600,
        '@media (min-width: 768px)': {
          fontSize: 'var(--vera-typography-caption-semibold-font-size, 0.75rem)',
          lineHeight: 'var(--vera-typography-caption-semibold-line-height, 1rem)',
          fontWeight: 'var(--vera-typography-caption-semibold-font-weight, 600)',
        },
      };

      fontWeightUtilities['.font-vera-caption-semibold'] = {
        fontWeight: 600,
        '@media (min-width: 768px)': {
          fontWeight: 'var(--vera-typography-caption-semibold-font-weight, 600)',
        },
      };

      addUtilities(fontSizeUtilities);
      addUtilities(fontWeightUtilities);
    },
    {
      theme: {
        extend: {
          borderRadius: {
            'vera-extra-large': 'var(--vera-border-radius-extra-large, 24px)',
            'vera-extra-small': 'var(--vera-border-radius-extra-small, 2px)',
            'vera-large': 'var(--vera-border-radius-large, 12px)',
            'vera-medium': 'var(--vera-border-radius-medium, 8px)',
            'vera-none': 'var(--vera-border-radius-none, 0px)',
            'vera-small': 'var(--vera-border-radius-small, 4px)',
          },
          colors: {
            'vera-accent': 'var(--vera-accent, #FFFFFF)',
            'vera-accent-light': 'var(--vera-accent-light, #FFFFFF)',
            'vera-accent-dark': 'var(--vera-accent-dark, #FFFFFF)',
            'vera-alert-background': 'var(--vera-alert-background, #FFEEF2)',
            'vera-alert-background-light': 'var(--vera-alert-background-light, #FFEEF2)',
            'vera-alert-background-dark': 'var(--vera-alert-background-dark, #3E0004)',
            'vera-alert-background-hover': 'var(--vera-alert-background-hover, #FEDFDF)',
            'vera-alert-background-hover-light':
              'var(--vera-alert-background-hover-light, #FEDFDF)',
            'vera-alert-background-hover-dark': 'var(--vera-alert-background-hover-dark, #6E0000)',
            'vera-alert-text': 'var(--vera-alert-text, #CD0000)',
            'vera-alert-text-light': 'var(--vera-alert-text-light, #CD0000)',
            'vera-alert-text-dark': 'var(--vera-alert-text-dark, #FEDFDF)',
            'vera-background': 'var(--vera-background, #F5F0FD)',
            'vera-background-light': 'var(--vera-background-light, #F5F0FD)',
            'vera-background-dark': 'var(--vera-background-dark, #26044D)',
            'vera-border': 'var(--vera-border, #E6E6E6)',
            'vera-border-light': 'var(--vera-border-light, #E6E6E6)',
            'vera-border-dark': 'var(--vera-border-dark, #333333)',
            'vera-dark-background': 'var(--vera-dark-background, #202124)',
            'vera-dark-background-light': 'var(--vera-dark-background-light, #202124)',
            'vera-dark-background-dark': 'var(--vera-dark-background-dark, #202124)',
            'vera-dark-grey': 'var(--vera-dark-grey, #333333)',
            'vera-dark-grey-light': 'var(--vera-dark-grey-light, #333333)',
            'vera-dark-grey-dark': 'var(--vera-dark-grey-dark, #333333)',
            'vera-dark-grey-hover': 'var(--vera-dark-grey-hover, #292828)',
            'vera-dark-grey-hover-light': 'var(--vera-dark-grey-hover-light, #292828)',
            'vera-dark-grey-hover-dark': 'var(--vera-dark-grey-hover-dark, #292828)',
            'vera-dark-grey-opacity': 'var(--vera-dark-grey-opacity, #333333CD)',
            'vera-dark-grey-opacity-light': 'var(--vera-dark-grey-opacity-light, #333333CD)',
            'vera-dark-grey-opacity-dark': 'var(--vera-dark-grey-opacity-dark, #333333CD)',
            'vera-disabled': 'var(--vera-disabled, #E6E6E6)',
            'vera-disabled-light': 'var(--vera-disabled-light, #E6E6E6)',
            'vera-disabled-dark': 'var(--vera-disabled-dark, #333333)',
            'vera-error': 'var(--vera-error, #E61D1D)',
            'vera-error-light': 'var(--vera-error-light, #E61D1D)',
            'vera-error-dark': 'var(--vera-error-dark, #F75959)',
            'vera-error-hover': 'var(--vera-error-hover, #CD0000)',
            'vera-error-hover-light': 'var(--vera-error-hover-light, #CD0000)',
            'vera-error-hover-dark': 'var(--vera-error-hover-dark, #FE9696)',
            'vera-information': 'var(--vera-information, #0276D5)',
            'vera-information-light': 'var(--vera-information-light, #0276D5)',
            'vera-information-dark': 'var(--vera-information-dark, #2997F0)',
            'vera-information-background': 'var(--vera-information-background, #E8F4FB)',
            'vera-information-background-light':
              'var(--vera-information-background-light, #E8F4FB)',
            'vera-information-background-dark': 'var(--vera-information-background-dark, #E8F4FB)',
            'vera-information-hover': 'var(--vera-information-hover, #2997F0)',
            'vera-information-hover-light': 'var(--vera-information-hover-light, #2997F0)',
            'vera-information-hover-dark': 'var(--vera-information-hover-dark, #0276D5)',
            'vera-on-accent': 'var(--vera-on-accent, #000000)',
            'vera-on-accent-light': 'var(--vera-on-accent-light, #000000)',
            'vera-on-accent-dark': 'var(--vera-on-accent-dark, #000000)',
            'vera-on-background': 'var(--vera-on-background, #757575)',
            'vera-on-background-light': 'var(--vera-on-background-light, #757575)',
            'vera-on-background-dark': 'var(--vera-on-background-dark, #B3B3B3)',
            'vera-on-dark-grey': 'var(--vera-on-dark-grey, #FFFFFF)',
            'vera-on-dark-grey-light': 'var(--vera-on-dark-grey-light, #FFFFFF)',
            'vera-on-dark-grey-dark': 'var(--vera-on-dark-grey-dark, #FFFFFF)',
            'vera-on-error': 'var(--vera-on-error, #FFFFFF)',
            'vera-on-error-light': 'var(--vera-on-error-light, #FFFFFF)',
            'vera-on-error-dark': 'var(--vera-on-error-dark, #000000)',
            'vera-on-information': 'var(--vera-on-information, #FFFFFF)',
            'vera-on-information-light': 'var(--vera-on-information-light, #FFFFFF)',
            'vera-on-information-dark': 'var(--vera-on-information-dark, #FFFFFF)',
            'vera-on-primary': 'var(--vera-on-primary, #FFFFFF)',
            'vera-on-primary-light': 'var(--vera-on-primary-light, #FFFFFF)',
            'vera-on-primary-dark': 'var(--vera-on-primary-dark, #000000)',
            'vera-on-secondary': 'var(--vera-on-secondary, #FFFFFF)',
            'vera-on-secondary-light': 'var(--vera-on-secondary-light, #FFFFFF)',
            'vera-on-secondary-dark': 'var(--vera-on-secondary-dark, #000000)',
            'vera-on-success': 'var(--vera-on-success, #FFFFFF)',
            'vera-on-success-light': 'var(--vera-on-success-light, #FFFFFF)',
            'vera-on-success-dark': 'var(--vera-on-success-dark, #000000)',
            'vera-on-surface': 'var(--vera-on-surface, #929292)',
            'vera-on-surface-light': 'var(--vera-on-surface-light, #929292)',
            'vera-on-surface-dark': 'var(--vera-on-surface-dark, #FFFFFF)',
            'vera-on-tertiary': 'var(--vera-on-tertiary, #FFFFFF)',
            'vera-on-tertiary-light': 'var(--vera-on-tertiary-light, #FFFFFF)',
            'vera-on-tertiary-dark': 'var(--vera-on-tertiary-dark, #000000)',
            'vera-on-warning': 'var(--vera-on-warning, #FFFFFF)',
            'vera-on-warning-light': 'var(--vera-on-warning-light, #FFFFFF)',
            'vera-on-warning-dark': 'var(--vera-on-warning-dark, #000000)',
            'vera-primary': 'var(--vera-primary, #9941FF)',
            'vera-primary-light': 'var(--vera-primary-light, #9941FF)',
            'vera-primary-dark': 'var(--vera-primary-dark, #B27BF2)',
            'vera-primary-hover': 'var(--vera-primary-hover, #871EFF)',
            'vera-primary-hover-light': 'var(--vera-primary-hover-light, #871EFF)',
            'vera-primary-hover-dark': 'var(--vera-primary-hover-dark, #CBA1FA)',
            'vera-secondary': 'var(--vera-secondary, #000000)',
            'vera-secondary-light': 'var(--vera-secondary-light, #000000)',
            'vera-secondary-dark': 'var(--vera-secondary-dark, #FFFFFF)',
            'vera-secondary-hover': 'var(--vera-secondary-hover, #666666)',
            'vera-secondary-hover-light': 'var(--vera-secondary-hover-light, #666666)',
            'vera-secondary-hover-dark': 'var(--vera-secondary-hover-dark, #929292)',
            'vera-skeleton-like': 'var(--vera-skeleton-like, #B3B3B3)',
            'vera-skeleton-like-light': 'var(--vera-skeleton-like-light, #B3B3B3)',
            'vera-skeleton-like-dark': 'var(--vera-skeleton-like-dark, #333333)',
            'vera-success': 'var(--vera-success, #1C8731)',
            'vera-success-light': 'var(--vera-success-light, #1C8731)',
            'vera-success-dark': 'var(--vera-success-dark, #30A849)',
            'vera-success-hover': 'var(--vera-success-hover, #1F7629)',
            'vera-success-hover-light': 'var(--vera-success-hover-light, #1F7629)',
            'vera-success-hover-dark': 'var(--vera-success-hover-dark, #53CA6A)',
            'vera-surface': 'var(--vera-surface, #FFFFFF)',
            'vera-surface-light': 'var(--vera-surface-light, #FFFFFF)',
            'vera-surface-dark': 'var(--vera-surface-dark, #000000)',
            'vera-tertiary': 'var(--vera-tertiary, #757575)',
            'vera-tertiary-light': 'var(--vera-tertiary-light, #757575)',
            'vera-tertiary-dark': 'var(--vera-tertiary-dark, #B3B3B3)',
            'vera-tertiary-hover': 'var(--vera-tertiary-hover, #929292)',
            'vera-tertiary-hover-light': 'var(--vera-tertiary-hover-light, #929292)',
            'vera-tertiary-hover-dark': 'var(--vera-tertiary-hover-dark, #B3B3B3)',
            'vera-text-disabled': 'var(--vera-text-disabled, #B3B3B3)',
            'vera-text-disabled-light': 'var(--vera-text-disabled-light, #B3B3B3)',
            'vera-text-disabled-dark': 'var(--vera-text-disabled-dark, #666666)',
            'vera-text-primary': 'var(--vera-text-primary, #9941FF)',
            'vera-text-primary-light': 'var(--vera-text-primary-light, #9941FF)',
            'vera-text-primary-dark': 'var(--vera-text-primary-dark, #B27BF2)',
            'vera-text-secondary': 'var(--vera-text-secondary, #000000)',
            'vera-text-secondary-light': 'var(--vera-text-secondary-light, #000000)',
            'vera-text-secondary-dark': 'var(--vera-text-secondary-dark, #FFFFFF)',
            'vera-text-tertiary': 'var(--vera-text-tertiary, #757575)',
            'vera-text-tertiary-light': 'var(--vera-text-tertiary-light, #757575)',
            'vera-text-tertiary-dark': 'var(--vera-text-tertiary-dark, #B3B3B3)',
            'vera-warning': 'var(--vera-warning, #BE5702)',
            'vera-warning-light': 'var(--vera-warning-light, #BE5702)',
            'vera-warning-dark': 'var(--vera-warning-dark, #FA9F00)',
            'vera-warning-hover': 'var(--vera-warning-hover, #A64C03)',
            'vera-warning-hover-light': 'var(--vera-warning-hover-light, #A64C03)',
            'vera-warning-hover-dark': 'var(--vera-warning-hover-dark, #FACC4B)',
          },
          fontFamily: {
            'vera-plain': [
              'var(--vera-font-family-plain, Inter, sans-serif, system-ui, ui-sans-serif, Marker Felt, Trebuchet MS)',
            ],
          },
          screens: {
            'vera-mobile': {
              max: '767px',
            },
            'vera-desktop': {
              min: '768px',
            },
          },
        },
      },
    }
  );
};

veraUI.safelist = ['vera-dark-mode'];

module.exports = veraUI;
