#!/bin/bash
# Generated by `yarn sync:env` from app-config.json and scripts/generateEnv.ts.
# Do not edit by hand; changes are overwritten on the next sync. Project defaults that are not
# generated live in env.defaults.sh, sourced at the end of this file.

# App
export ENABLE_REPORT_ISSUE=true
export SHOW_VIDEO_STATS=false

# Localization
export I18N_FALLBACK_LANGUAGE='en'
export I18N_SUPPORTED_LANGUAGES='en|en-US|es|es-MX|it|de|ja'

# Video
export ALLOW_BACKGROUND_EFFECTS=true
export ALLOW_CAMERA_CONTROL=true
export ALLOW_VIDEO_ON_JOIN=true
export DEFAULT_RESOLUTION='1280x720'

# Audio
export ALLOW_ADVANCED_NOISE_SUPPRESSION=true
export ALLOW_AUDIO_ON_JOIN=true
export ALLOW_MICROPHONE_CONTROL=true

# Waiting room
export WAITING_ROOM_ALLOW_DEVICE_SELECTION=true
export WAITING_ROOM_ALLOW_ADVANCED_SETTINGS=true
export BYPASS_WAITING_ROOM=false

# Meeting room
export MEETING_ROOM_ALLOW_DEVICE_SELECTION=true
export DEVICE_SELECTION=true
export MEETING_ROOM_ALLOW_ADVANCED_SETTINGS=true
export ALLOW_ARCHIVING=true
export ALLOW_CAPTIONS=true
export ALLOW_CHAT=true
export ALLOW_EMOJIS=true
export ALLOW_SCREEN_SHARE=true
export DEFAULT_LAYOUT_MODE='active-speaker'
export SHOW_PARTICIPANT_LIST=true

source "$(dirname "${BASH_SOURCE[0]}")/env.defaults.sh"
