#!/usr/bin/env tsx
/**
 * Generates env.sh from app-config.json (the source of truth for frontend settings). The generated
 * file ends by sourcing env.defaults.sh, which holds every project default that is not generated.
 * Run: yarn sync:env
 *
 * env.sh is a generated artifact; do not edit it by hand. Update app-config.json or env.defaults.sh.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';

const commandName = 'sync:env';

const configFilePath = path.resolve('app-config.json');
const outputFilePath = path.resolve('env.sh');

// 'string' is single-quoted; 'raw' is unquoted (booleans and numbers).
type ValueFormat = 'string' | 'raw';

type DerivedEnvVariable = {
  name: string;
  sourcePath: string;
  format: ValueFormat;
  join?: string;
  // Translates a shared config value to what the web app expects when the enums differ.
  valueMap?: Record<string, string>;
};

type EnvVariableGroup = {
  comments: string[];
  variables: DerivedEnvVariable[];
};

const fileHeaderComments = [
  'Generated by `yarn sync:env` from app-config.json and scripts/generateEnv.ts.',
  'Do not edit by hand; changes are overwritten on the next sync. Project defaults that are not',
  'generated live in env.defaults.sh, sourced at the end of this file.',
];

// Resolved from this file's own location, so env.sh can be sourced from any directory (bash only).
const defaultsImportLine = 'source "$(dirname "${BASH_SOURCE[0]}")/env.defaults.sh"';

const envVariableGroups: EnvVariableGroup[] = [
  {
    comments: ['App'],
    variables: [
      { name: 'ENABLE_REPORT_ISSUE', sourcePath: 'appSettings.enableReportIssue', format: 'raw' },
      { name: 'SHOW_VIDEO_STATS', sourcePath: 'appSettings.showVideoStats', format: 'raw' },
    ],
  },
  {
    comments: ['Localization'],
    variables: [
      {
        name: 'I18N_FALLBACK_LANGUAGE',
        sourcePath: 'localizationSettings.fallbackLanguage',
        format: 'string',
      },
      {
        name: 'I18N_SUPPORTED_LANGUAGES',
        sourcePath: 'localizationSettings.supportedLanguages',
        format: 'string',
        join: '|',
      },
    ],
  },
  {
    comments: ['Video'],
    variables: [
      {
        name: 'ALLOW_BACKGROUND_EFFECTS',
        sourcePath: 'videoSettings.allowBackgroundEffects',
        format: 'raw',
      },
      {
        name: 'ALLOW_CAMERA_CONTROL',
        sourcePath: 'videoSettings.allowCameraControl',
        format: 'raw',
      },
      { name: 'ALLOW_VIDEO_ON_JOIN', sourcePath: 'videoSettings.allowVideoOnJoin', format: 'raw' },
      {
        name: 'DEFAULT_RESOLUTION',
        sourcePath: 'videoSettings.defaultResolution',
        format: 'string',
      },
    ],
  },
  {
    comments: ['Audio'],
    variables: [
      {
        name: 'ALLOW_ADVANCED_NOISE_SUPPRESSION',
        sourcePath: 'audioSettings.allowAdvancedNoiseSuppression',
        format: 'raw',
      },
      { name: 'ALLOW_AUDIO_ON_JOIN', sourcePath: 'audioSettings.allowAudioOnJoin', format: 'raw' },
      {
        name: 'ALLOW_MICROPHONE_CONTROL',
        sourcePath: 'audioSettings.allowMicrophoneControl',
        format: 'raw',
      },
    ],
  },
  {
    comments: ['Waiting room'],
    variables: [
      {
        name: 'WAITING_ROOM_ALLOW_DEVICE_SELECTION',
        sourcePath: 'waitingRoomSettings.allowDeviceSelection',
        format: 'raw',
      },
      {
        name: 'WAITING_ROOM_ALLOW_ADVANCED_SETTINGS',
        sourcePath: 'waitingRoomSettings.allowSettings',
        format: 'raw',
      },
      {
        name: 'BYPASS_WAITING_ROOM',
        sourcePath: 'waitingRoomSettings.bypassWaitingRoom',
        format: 'raw',
      },
    ],
  },
  {
    comments: ['Meeting room'],
    variables: [
      {
        name: 'MEETING_ROOM_ALLOW_DEVICE_SELECTION',
        sourcePath: 'meetingRoomSettings.allowDeviceSelection',
        format: 'raw',
      },
      {
        name: 'DEVICE_SELECTION',
        sourcePath: 'meetingRoomSettings.allowDeviceSelection',
        format: 'raw',
      },
      {
        name: 'MEETING_ROOM_ALLOW_ADVANCED_SETTINGS',
        sourcePath: 'meetingRoomSettings.allowSettings',
        format: 'raw',
      },
      { name: 'ALLOW_ARCHIVING', sourcePath: 'meetingRoomSettings.allowArchiving', format: 'raw' },
      { name: 'ALLOW_CAPTIONS', sourcePath: 'meetingRoomSettings.allowCaptions', format: 'raw' },
      { name: 'ALLOW_CHAT', sourcePath: 'meetingRoomSettings.allowChat', format: 'raw' },
      { name: 'ALLOW_EMOJIS', sourcePath: 'meetingRoomSettings.allowEmojis', format: 'raw' },
      {
        name: 'ALLOW_SCREEN_SHARE',
        sourcePath: 'meetingRoomSettings.allowScreenShare',
        format: 'raw',
      },
      {
        name: 'DEFAULT_LAYOUT_MODE',
        sourcePath: 'meetingRoomSettings.defaultLayoutMode',
        format: 'string',
        // Schema enum is 'activeSpeaker'; the web app expects 'active-speaker'.
        valueMap: { activeSpeaker: 'active-speaker' },
      },
      {
        name: 'SHOW_PARTICIPANT_LIST',
        sourcePath: 'meetingRoomSettings.showParticipantList',
        format: 'raw',
      },
    ],
  },
];

function readConfig(): Record<string, unknown> {
  if (!fs.existsSync(configFilePath)) {
    console.error(`\x1b[31m✖ Config source not found at ${configFilePath}\x1b[0m`);
    process.exit(1);
  }

  const raw = fs.readFileSync(configFilePath, 'utf-8');

  try {
    return JSON.parse(raw) as Record<string, unknown>;
  } catch (error) {
    console.error(`\x1b[31m✖ Failed to parse ${configFilePath} as JSON\x1b[0m`, error);
    process.exit(1);
  }
}

function resolvePath(config: Record<string, unknown>, sourcePath: string): unknown {
  const value = sourcePath.split('.').reduce<unknown>((current, key) => {
    if (current === null || typeof current !== 'object') return undefined;
    return (current as Record<string, unknown>)[key];
  }, config);

  if (value === undefined) {
    console.error(`\x1b[31m✖ Missing value in app-config.json for path "${sourcePath}"\x1b[0m`);
    process.exit(1);
  }

  return value;
}

function escapeSingleQuoted(value: string): string {
  return value.replaceAll("'", String.raw`'\''`);
}

function serializeValue(value: unknown, args: { format: ValueFormat; join?: string }): string {
  const scalar = Array.isArray(value) ? value.join(args.join ?? '|') : String(value);

  return args.format === 'string' ? `'${escapeSingleQuoted(scalar)}'` : scalar;
}

function resolveValue(variable: DerivedEnvVariable, config: Record<string, unknown>): unknown {
  const value = resolvePath(config, variable.sourcePath);

  if (variable.valueMap && typeof value === 'string' && value in variable.valueMap) {
    return variable.valueMap[value];
  }

  return value;
}

function buildExportLine(variable: DerivedEnvVariable, config: Record<string, unknown>): string {
  const value = resolveValue(variable, config);

  return `export ${variable.name}=${serializeValue(value, variable)}`;
}

function buildCommentLines(comments: string[]): string[] {
  return comments.map((comment) => `# ${comment}`);
}

function buildEnvFileContents(config: Record<string, unknown>): string {
  const groupBlocks = envVariableGroups.map((group) =>
    [
      ...buildCommentLines(group.comments),
      ...group.variables.map((variable) => buildExportLine(variable, config)),
    ].join('\n')
  );

  const header = ['#!/bin/bash', ...buildCommentLines(fileHeaderComments)].join('\n');

  return `${[header, ...groupBlocks, defaultsImportLine].join('\n\n')}\n`;
}

const generateEnv = () => {
  console.log(`\x1b[36m🔄 [${commandName}] Generating env.sh from app-config.json\x1b[0m\n`);

  const config = readConfig();
  const contents = buildEnvFileContents(config);

  fs.writeFileSync(outputFilePath, contents, 'utf-8');

  console.log(`\x1b[32m✔ [${commandName}] Wrote ${outputFilePath}\x1b[0m`);
};

generateEnv();
