name: auto-update-dependencies

on:
  push:
    # branches:
    #   - develop

permissions:
  contents: read

env:
  BRANCH_NAME: ${{ github.ref_name }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_REPOSITORY: ${{ github.repository }}

jobs:
  run:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: yarn install
      - name: Run dependency update script
        run: node scripts/generateDependenciesList.js
      - name: Auto-commit updated dependencies file
        run: |
          echo "Committing docs/DEPENDENCIES.md changes..."
          FILE="docs/DEPENDENCIES.md"
          CONTENT=$(base64 -w 0 "$FILE")
          SHA=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/$GITHUB_REPOSITORY/contents/$FILE?ref=$BRANCH_NAME" | jq -r .sha)
          if [ "$SHA" == "null" ]; then
            SHA=""
          fi
          curl -s -X PUT -H "Authorization: token $GITHUB_TOKEN" \
            -d "{\"message\":\"Commit updated dependencies file [auto-generated]\", \"content\":\"$CONTENT\", \"branch\":\"$BRANCH_NAME\", \"sha\":\"$SHA\"}" \
            "https://api.github.com/repos/$GITHUB_REPOSITORY/contents/$FILE"
