name: check-pull-request-title

on:
  pull_request:
    types: [edited, opened]

permissions:
  contents: read

jobs:
  run:
    name: >
      Check format is `<type>(scope): [JIRA-####] <description>`
    runs-on: ubuntu-22.04
    steps:
      - uses: amannn/action-semantic-pull-request@v5.5.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            fix
            feat
            chore
          scopes: |
            core
            ui
            ci
            docs
          requireScope: true
          subjectPattern: ^\[[A-Z]{5,}-\d{4,}\].+$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            didn't match the configured pattern. Please ensure that the subject
            contains the JIRA ticket.
