name: Delete VCR Instance on Merge

on:
  pull_request:
    types: [closed]

# avoid running more than one workflow per PR in repo
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  delete-vcr-instance:
    runs-on: [vcp-runner]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22.4
          cache: npm

      - name: Install VCR CLI
        run: |
          sudo curl -L https://raw.githubusercontent.com/Vonage/cloud-runtime-cli/main/script/install.sh | sudo sh
          vcr -v

      - name: Get instance_id from PR comment
        id: get_instance_id
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
            });
            const match = comments
              .map(c => c.body.match(/<!-- instance_id:(.+) -->/))
              .find(Boolean);
            if (!match) throw new Error('No instance_id found in PR comments');
            core.setOutput('instance_id', match[1]);

      - name: Echo instance_id
        run: |
          echo "Instance ID: ${{ steps.get_instance_id.outputs.instance_id }}"

      # - name: Delete VCR instance
      #   run: |
      #     vcr instance remove --id ${{ steps.get_instance_id.outputs.instance_id }} --app-id ${{ secrets.APP_ID }} --api-key ${{ secrets.VCR_API_KEY }} --api-secret ${{ secrets.VCR_API_SECRET }}
