name: Deploy to VCR on Commit Push

on:
  pull_request:
    branches-ignore:
      - main
      - develop

permissions:
  contents: write
  pull-requests: write

jobs:
  build-and-test:
    runs-on: [vcp-runner]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 22.4
          cache: npm

      - name: Install VCR CLI
        run: |
          sudo curl -L https://raw.githubusercontent.com/Vonage/cloud-runtime-cli/main/script/install.sh | sudo sh
          vcr -v

      - name: Prepare manifest for unique deployment
        run: |
          cp vcr-gha.yml vcr-gha.temp.yml
          BRANCH_NAME=$(echo "${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" | tr '/' '-')
          sed -i "s/name: vonage-video-react-app/name: vonage-video-react-app-$BRANCH_NAME/g" vcr-gha.temp.yml
          sed -i 's/<DOMAIN>//g' vcr-gha.temp.yml

      - name: Deploy vcr
        id: deploy
        run: |
          vcr deploy --filename vcr-gha.yml --app-id ${{ secrets.APP_ID }} --api-key ${{ secrets.VCR_API_KEY }} --api-secret ${{ secrets.VCR_API_SECRET }} --region aws.euw1 --graphql-endpoint https://graphql.euw1.runtime.vonage.cloud/v1/graphql --timeout=15m 2>&1 | tee deploy-vcr-logs.log
          VCR_URL=$(grep -oE 'https://[a-zA-Z0-9.-]+\.vonage\.cloud' deploy-vcr-logs.log | head -1)
          echo "vcr_url=$VCR_URL" >> $GITHUB_OUTPUT

      - name: Comment the VCR instance link on PR
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            🚀 VCR instance deployed for commit `${{ github.sha }}`
            [View VCR Instance](${{ steps.deploy.outputs.vcr_url }})
