name: Deploy to VCR on PR

on:
  pull_request:
    types: [opened, labeled]

permissions:
  contents: write
  pull-requests: write

# avoid running more than one workflow per PR in repo
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: [vcp-runner]
    if: github.event.action == 'opened' || github.event.label.name == 'vcr-deploy'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22.4
          cache: npm

      - name: Install VCR CLI
        run: |
          sudo curl -L https://raw.githubusercontent.com/Vonage/cloud-runtime-cli/main/script/install.sh | sudo sh
          vcr -v

      - name: Replace some values in the manifest so that it does not break other deployments and is unique
        run: |
          cp vcr-gha.yml vcr-gha.temp.yml
          sed -i "s/name: vonage-video-react-app/name: vonage-video-react-app-${{ github.event.pull_request.number }}/g" vcr-gha.temp.yml
          sed -i 's/<DOMAIN>//g' vcr-gha.temp.yml

      - name: Deploy vcr
        id: deploy
        run: |
          vcr deploy --filename vcr-gha.temp.yml --app-id ${{ secrets.APP_ID }} --api-key ${{ secrets.VCR_API_KEY }} --api-secret ${{ secrets.VCR_API_SECRET }} --region aws.euw1 --graphql-endpoint https://graphql.euw1.runtime.vonage.cloud/v1/graphql --timeout=15m 2>&1 | tee deploy-vcr-logs.log
          VCR_URL=$(grep -oE 'https://[a-zA-Z0-9.-]+\.vonage\.cloud' deploy-vcr-logs.log | head -1)
          INSTANCE_ID=$(grep -oE 'Instance id: [a-z0-9-]+' deploy-vcr-logs.log | head -1 | awk '{print $3}')
          echo "vcr_url=$VCR_URL" >> $GITHUB_OUTPUT
          echo "instance_id=$INSTANCE_ID" >> $GITHUB_OUTPUT

      - name: Comment VCR instance link
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            <!-- instance_id:${{ steps.deploy.outputs.instance_id }} -->
            🚀 VCR instance deployed for the pull requests: `${{ github.event.pull_request.number }}`
            [View VCR Instance](${{ steps.deploy.outputs.vcr_url }})
