name: Deploy to VCR on PR

on:
  pull_request:
    types: [opened, labeled]

permissions:
  contents: write
  pull-requests: write

# avoid running more than one workflow per PR in repo
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: [vcp-runner]
    if: github.event.action == 'opened' || github.event.label.name == 'vcr-deploy'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22.4
          cache: npm

      - name: Install VCR CLI
        run: |
          sudo curl -L https://raw.githubusercontent.com/Vonage/cloud-runtime-cli/main/script/install.sh | sudo sh
          vcr -v

      - name: Replace some values in the manifest so that it does not break other deployments and is unique
        run: |
          cp vcr-gha.yml vcr-gha.temp.yml
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          sed -i "s/name: vonage-video-react-app/name: vonage-video-react-app-$SHORT_SHA/g" vcr-gha.temp.yml
          sed -i 's/<DOMAIN>//g' vcr-gha.temp.yml

      - name: Deploy vcr
        id: deploy
        run: |
          vcr deploy --filename vcr-gha.temp.yml --app-id ${{ secrets.APP_ID }} --api-key ${{ secrets.VCR_API_KEY }} --api-secret ${{ secrets.VCR_API_SECRET }} --region aws.euw1 --graphql-endpoint https://graphql.euw1.runtime.vonage.cloud/v1/graphql --timeout=15m 2>&1 | tee deploy-vcr-logs.log
          VCR_URL=$(grep -oE 'https://[a-zA-Z0-9.-]+\.vonage\.cloud' deploy-vcr-logs.log | head -1)
          INSTANCE_ID=$(grep -oE 'Instance ID: [a-zA-Z0-9-]+' deploy-vcr-logs.log | head -1 | awk '{print $3}')
          echo "vcr_url=$VCR_URL" >> $GITHUB_OUTPUT
          echo "$INSTANCE_ID" > instance_id.txt

      - name: Show deploy-vcr-logs.log
        run: cat deploy-vcr-logs.log

      # This is needed to be able to use the instance_id in the cleanup workflow
      - name: Upload instance_id artifact
        uses: actions/upload-artifact@v4
        with:
          name: instance_id
          path: instance_id.txt

      - name: Comment the VCR instance link on PR
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            🚀 VCR instance deployed for the commit hash: `${{ github.sha }}`
            [View VCR Instance](${{ steps.deploy.outputs.vcr_url }})
