name: Deploy to VCR on Commit Push

on:
  push:
    branches-ignore:
      - main
      - develop

permissions:
  contents: read
  pull-requests: write

jobs:
  build-and-test:
    runs-on: [vcp-runner]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 22.4
          cache: npm

      - name: Install VCR CLI
        run: |
          sudo curl -L https://raw.githubusercontent.com/Vonage/cloud-runtime-cli/main/script/install.sh | sudo sh
          vcr -v

      - name: Deploy vcr
        id: deploy
        run: |
          sed -i 's/<DOMAIN>//g' "${{ github.workspace }}/vcr-gha.yml"
          vcr deploy --filename vcr-gha.yml --app-id ${{ secrets.APP_ID }} --api-key ${{ secrets.VCR_API_KEY }} --api-secret ${{ secrets.VCR_API_SECRET }} --region aws.euw1 --graphql-endpoint https://graphql.euw1.runtime.vonage.cloud/v1/graphql --timeout=15m 2>&1 | tee deploy-vcr-logs.log
          VCR_URL=$(grep -o 'https://[^ ]*vonage.cloud[^ ]*' deploy-vcr-logs.log | head -1)
          echo "vcr_url=$VCR_URL" >> $GITHUB_OUTPUT
          echo $VCR_URL

      - name: Comment VCR instance link on commit
        uses: peter-evans/commit-comment@v3
        with:
          body: |
            🚀 VCR instance deployed for commit `${{ github.sha }}`
            [View VCR Instance](${{ steps.deploy.outputs.vcr_url }})
