name: check-lint-issues

on: [pull_request, workflow_dispatch]

permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: [self-hosted]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: npm

      - name: Install Dependencies
        run: |
          node -v
          npm -v
          npm install --global yarn
          yarn

      - name: Check for lint issues
        run: |
          yarn lint && yarn prettier . --check

      - name: Check for TS errors
        run: |
          yarn ts-check

      - name: Check that new files are camelCase
        run: |
          yarn lint:filenames

      - name: Validate PR title
        run: |
          set -e

          pr_name="${{ github.event.pull_request.title }}"
          echo "PR Title: '$pr_name'"

          # Regex to check following:
          # Starts with "VIDCS-" followed by digits
          # A colon (:) followed by exactly one space
          # followed by the actual PR title text
          regex="^VIDCS-[0-9]+: [^ ].*$"

          if [[ "$pr_name" =~ $regex ]]; then
            echo "Acceptable title"
            exit 0
          else
            echo "Rejected title"
            echo "Reason: The PR title must start with 'VIDCS-' followed by digits, a colon (:), and exactly one space, with the rest of the title immediately after the space."
            exit 1
          fi
        shell: bash

      - name: Run license check
        run: |
          npx license-checker --json > scripts/allLicenseResults.json
          node scripts/licenseCheck.js
