name: Notify Slack on Release

on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-22.04
    steps:
      - name: Send to slack channels
        uses: slackapi/slack-github-action@v2.0.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          webhook-type: incoming-webhook
          errors: true
          payload: |
            blocks:
              - type: "header"
                text:
                  type: "plain_text"
                  text: ":tada: Version ${{ github.event.release.name }} of the Vonage Video Reference App Just Released!"
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "${{ github.event.release.body }}"
              - type: "divider"
              - type: "actions"
                text:
                  type: "mrkdwn"
                  text: "You can view the full change log <${{github.event.release.html_url }}|here>"
